/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer
/**
 * 
 * @param headerTitle 
 * @param content 
 * @param skip 
 * @param placeholder 
 * @param invalidTitle 
 * @param invalidMessage 
 */
@Serializable
data class AccessCode (
    @SerialName(value = "headerTitle") @Required val headerTitle: kotlin.String,
    @SerialName(value = "content") @Required val content: kotlin.String,
    @SerialName(value = "skip") @Required val skip: kotlin.String,
    @SerialName(value = "placeholder") @Required val placeholder: kotlin.String,
    @SerialName(value = "invalidTitle") @Required val invalidTitle: kotlin.String,
    @SerialName(value = "invalidMessage") @Required val invalidMessage: kotlin.String
) 



