/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer
/**
 * 
 * @param yourContent 
 * @param following 
 * @param myActivity 
 * @param title 
 * @param typeLike 
 * @param typeComment 
 * @param typePost 
 * @param typeMention 
 * @param titleError 
 * @param youLiked 
 * @param someonesPhoto 
 * @param liked 
 * @param youCommented 
 * @param commentedOnArticle 
 * @param likedAArticle 
 * @param you 
 * @param commentedOn 
 * @param yourPhoto 
 * @param youMentioned 
 * @param yourself 
 * @param mentioned 
 * @param noActivity 
 * @param typeArticle 
 * @param youFollow 
 * @param isFollowing 
 * @param aPhoto 
 * @param anArticle 
 * @param someonesArticle 
 * @param typeArticleLike 
 * @param typeArticleComment 
 * @param aComment 
 * @param someonesComment 
 * @param yourArticle 
 * @param yourComment 
 * @param youUnfollowed 
 * @param youFollowed 
 * @param followed 
 * @param unfollowed 
 * @param someone 
 * @param inSomething 
 * @param deny 
 * @param approve 
 * @param wantsToAddYou 
 */
@Serializable
data class Activity (
    @SerialName(value = "yourContent") @Required val yourContent: kotlin.String,
    @SerialName(value = "following") @Required val following: kotlin.String,
    @SerialName(value = "myActivity") @Required val myActivity: kotlin.String,
    @SerialName(value = "title") @Required val title: kotlin.String,
    @SerialName(value = "typeLike") @Required val typeLike: kotlin.String,
    @SerialName(value = "typeComment") @Required val typeComment: kotlin.String,
    @SerialName(value = "typePost") @Required val typePost: kotlin.String,
    @SerialName(value = "typeMention") @Required val typeMention: kotlin.String,
    @SerialName(value = "titleError") @Required val titleError: kotlin.String,
    @SerialName(value = "youLiked") @Required val youLiked: kotlin.String,
    @SerialName(value = "someonesPhoto") @Required val someonesPhoto: kotlin.String,
    @SerialName(value = "liked") @Required val liked: kotlin.String,
    @SerialName(value = "youCommented") @Required val youCommented: kotlin.String,
    @SerialName(value = "commentedOnArticle") @Required val commentedOnArticle: kotlin.String,
    @SerialName(value = "likedAArticle") @Required val likedAArticle: kotlin.String,
    @SerialName(value = "you") @Required val you: kotlin.String,
    @SerialName(value = "commentedOn") @Required val commentedOn: kotlin.String,
    @SerialName(value = "yourPhoto") @Required val yourPhoto: kotlin.String,
    @SerialName(value = "youMentioned") @Required val youMentioned: kotlin.String,
    @SerialName(value = "yourself") @Required val yourself: kotlin.String,
    @SerialName(value = "mentioned") @Required val mentioned: kotlin.String,
    @SerialName(value = "noActivity") @Required val noActivity: kotlin.String,
    @SerialName(value = "typeArticle") @Required val typeArticle: kotlin.String,
    @SerialName(value = "youFollow") @Required val youFollow: kotlin.String,
    @SerialName(value = "isFollowing") @Required val isFollowing: kotlin.String,
    @SerialName(value = "aPhoto") @Required val aPhoto: kotlin.String,
    @SerialName(value = "anArticle") @Required val anArticle: kotlin.String,
    @SerialName(value = "someonesArticle") @Required val someonesArticle: kotlin.String,
    @SerialName(value = "typeArticleLike") @Required val typeArticleLike: kotlin.String,
    @SerialName(value = "typeArticleComment") @Required val typeArticleComment: kotlin.String,
    @SerialName(value = "aComment") @Required val aComment: kotlin.String,
    @SerialName(value = "someonesComment") @Required val someonesComment: kotlin.String,
    @SerialName(value = "yourArticle") @Required val yourArticle: kotlin.String,
    @SerialName(value = "yourComment") @Required val yourComment: kotlin.String,
    @SerialName(value = "youUnfollowed") @Required val youUnfollowed: kotlin.String,
    @SerialName(value = "youFollowed") @Required val youFollowed: kotlin.String,
    @SerialName(value = "followed") @Required val followed: kotlin.String,
    @SerialName(value = "unfollowed") @Required val unfollowed: kotlin.String,
    @SerialName(value = "someone") @Required val someone: kotlin.String,
    @SerialName(value = "inSomething") @Required val inSomething: kotlin.String,
    @SerialName(value = "deny") @Required val deny: kotlin.String,
    @SerialName(value = "approve") @Required val approve: kotlin.String,
    @SerialName(value = "wantsToAddYou") @Required val wantsToAddYou: kotlin.String
) 



