/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer
/**
 * 
 * @param guid 
 * @param answer 
 */
@Serializable
data class AnswerRequest (
    @SerialName(value = "guid") @Required val guid: kotlin.String,
    @SerialName(value = "answer") @Required val answer: kotlin.String
) 



