/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model

import dk.nodes.nstack.kotlin.codegen.model.AppOpenData
import dk.nodes.nstack.kotlin.codegen.model.AppOpenMeta

import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer
/**
 * 
 * @param data 
 * @param meta 
 */
@Serializable
data class AppopenV2 (
    @SerialName(value = "data") @Required val data: AppOpenData,
    @SerialName(value = "meta") @Required val meta: AppOpenMeta
) 



