/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer
/**
 * 
 * @param bookingError 
 * @param title 
 * @param subtitle 
 * @param phoneNumberTitle 
 * @param phoneNumberHint 
 * @param preferredArtistTitle 
 * @param preferredArtistHint 
 * @param describeTattooTitle 
 * @param describeTattooHint 
 * @param requestNowButton 
 * @param contactInformationButton 
 * @param bookingConfirmationTitle 
 * @param bookingConfirmationSubtitle 
 * @param bookingConfirmationButtonLabel 
 */
@Serializable
data class Booking (
    @SerialName(value = "bookingError") @Required val bookingError: kotlin.String,
    @SerialName(value = "title") @Required val title: kotlin.String,
    @SerialName(value = "subtitle") @Required val subtitle: kotlin.String,
    @SerialName(value = "phoneNumberTitle") @Required val phoneNumberTitle: kotlin.String,
    @SerialName(value = "phoneNumberHint") @Required val phoneNumberHint: kotlin.String,
    @SerialName(value = "preferredArtistTitle") @Required val preferredArtistTitle: kotlin.String,
    @SerialName(value = "preferredArtistHint") @Required val preferredArtistHint: kotlin.String,
    @SerialName(value = "describeTattooTitle") @Required val describeTattooTitle: kotlin.String,
    @SerialName(value = "describeTattooHint") @Required val describeTattooHint: kotlin.String,
    @SerialName(value = "requestNowButton") @Required val requestNowButton: kotlin.String,
    @SerialName(value = "contactInformationButton") @Required val contactInformationButton: kotlin.String,
    @SerialName(value = "bookingConfirmationTitle") @Required val bookingConfirmationTitle: kotlin.String,
    @SerialName(value = "bookingConfirmationSubtitle") @Required val bookingConfirmationSubtitle: kotlin.String,
    @SerialName(value = "bookingConfirmationButtonLabel") @Required val bookingConfirmationButtonLabel: kotlin.String
) 



