/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer
/**
 * 
 * @param currentPassword 
 * @param newPassword 
 * @param repeatNewPassword 
 * @param submit 
 * @param title 
 * @param changePasswordSuccess 
 * @param writeHere 
 * @param tooShort 
 * @param passwordsDontMatch 
 * @param required 
 * @param passwordsMatch 
 * @param passwordPlaceholder 
 */
@Serializable
data class ChangePassword (
    @SerialName(value = "currentPassword") @Required val currentPassword: kotlin.String,
    @SerialName(value = "newPassword") @Required val newPassword: kotlin.String,
    @SerialName(value = "repeatNewPassword") @Required val repeatNewPassword: kotlin.String,
    @SerialName(value = "submit") @Required val submit: kotlin.String,
    @SerialName(value = "title") @Required val title: kotlin.String,
    @SerialName(value = "changePasswordSuccess") @Required val changePasswordSuccess: kotlin.String,
    @SerialName(value = "writeHere") @Required val writeHere: kotlin.String,
    @SerialName(value = "tooShort") @Required val tooShort: kotlin.String,
    @SerialName(value = "passwordsDontMatch") @Required val passwordsDontMatch: kotlin.String,
    @SerialName(value = "required") @Required val required: kotlin.String,
    @SerialName(value = "passwordsMatch") @Required val passwordsMatch: kotlin.String,
    @SerialName(value = "passwordPlaceholder") @Required val passwordPlaceholder: kotlin.String
) 



