/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model

import dk.nodes.nstack.kotlin.codegen.model.Default1
import dk.nodes.nstack.kotlin.codegen.model.Errors1
import dk.nodes.nstack.kotlin.codegen.model.TranslateDefault
import dk.nodes.nstack.kotlin.codegen.model.TranslateErrors
import dk.nodes.nstack.kotlin.codegen.model.TranslateImport
import dk.nodes.nstack.kotlin.codegen.model.TranslateLanguages
import dk.nodes.nstack.kotlin.codegen.model.TranslateMain
import dk.nodes.nstack.kotlin.codegen.model.TranslatePlatformLanguages
import dk.nodes.nstack.kotlin.codegen.model.TranslatePlatforms

import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer
/**
 * 
 * @param default 
 * @param translatePlatforms 
 * @param translateDefault 
 * @param errors 
 * @param translateErrors 
 * @param translateLanguages 
 * @param translatePlatformLanguages 
 * @param translateMain 
 * @param translateImport 
 */
@Serializable
data class Data6 (
    @SerialName(value = "default") @Required val default: Default1,
    @SerialName(value = "translate_platforms") @Required val translatePlatforms: TranslatePlatforms,
    @SerialName(value = "translate_default") @Required val translateDefault: TranslateDefault,
    @SerialName(value = "errors") @Required val errors: Errors1,
    @SerialName(value = "translate_errors") @Required val translateErrors: TranslateErrors,
    @SerialName(value = "translate_languages") @Required val translateLanguages: TranslateLanguages,
    @SerialName(value = "translate_platform_languages") @Required val translatePlatformLanguages: TranslatePlatformLanguages,
    @SerialName(value = "translate_main") @Required val translateMain: TranslateMain,
    @SerialName(value = "translate_import") @Required val translateImport: TranslateImport
) 



