/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer
/**
 * 
 * @param ok 
 * @param required 
 * @param cancel 
 * @param done 
 * @param male 
 * @param female 
 * @param errorRandomErrorAlertText 
 * @param ago 
 * @param now 
 * @param open 
 * @param openLinkTitle 
 * @param openLinkMessage 
 * @param justNow 
 * @param aMinuteAgo 
 * @param anHourAgo 
 * @param hoursAgo 
 * @param yesterday 
 * @param week 
 * @param weeks 
 * @param month 
 * @param months 
 * @param minutesAgo 
 * @param youGotANewFollower 
 * @param dAgo 
 * @param sAgo 
 * @param retry 
 * @param back 
 * @param pressBackAgain 
 * @param picture 
 * @param fullSecond 
 * @param fullSeconds 
 * @param fullMinute 
 * @param fullMinutes 
 * @param fullHour 
 * @param fullHours 
 * @param fullDay 
 * @param fullDays 
 * @param fullWeek 
 * @param fullWeeks 
 * @param byLowercase 
 * @param monday 
 * @param tuesday 
 * @param wednesday 
 * @param thursday 
 * @param friday 
 * @param saturday 
 * @param sunday 
 * @param iCurrentlyWorkHere 
 * @param distanceAway 
 * @param km 
 * @param hey 
 * @param readMore 
 * @param edit 
 * @param save 
 * @param settings 
 * @param later 
 * @param next 
 * @param previous 
 * @param skip 
 * @param zhCN 
 * @param ptBR 
 * @param yes 
 * @param no 
 */
@Serializable
data class Default (
    @SerialName(value = "ok") @Required val ok: kotlin.String,
    @SerialName(value = "required") @Required val required: kotlin.String,
    @SerialName(value = "cancel") @Required val cancel: kotlin.String,
    @SerialName(value = "done") @Required val done: kotlin.String,
    @SerialName(value = "male") @Required val male: kotlin.String,
    @SerialName(value = "female") @Required val female: kotlin.String,
    @SerialName(value = "errorRandomErrorAlertText") @Required val errorRandomErrorAlertText: kotlin.String,
    @SerialName(value = "ago") @Required val ago: kotlin.String,
    @SerialName(value = "now") @Required val now: kotlin.String,
    @SerialName(value = "open") @Required val open: kotlin.String,
    @SerialName(value = "openLinkTitle") @Required val openLinkTitle: kotlin.String,
    @SerialName(value = "openLinkMessage") @Required val openLinkMessage: kotlin.String,
    @SerialName(value = "justNow") @Required val justNow: kotlin.String,
    @SerialName(value = "aMinuteAgo") @Required val aMinuteAgo: kotlin.String,
    @SerialName(value = "anHourAgo") @Required val anHourAgo: kotlin.String,
    @SerialName(value = "hoursAgo") @Required val hoursAgo: kotlin.String,
    @SerialName(value = "yesterday") @Required val yesterday: kotlin.String,
    @SerialName(value = "week") @Required val week: kotlin.String,
    @SerialName(value = "weeks") @Required val weeks: kotlin.String,
    @SerialName(value = "month") @Required val month: kotlin.String,
    @SerialName(value = "months") @Required val months: kotlin.String,
    @SerialName(value = "minutesAgo") @Required val minutesAgo: kotlin.String,
    @SerialName(value = "youGotANewFollower") @Required val youGotANewFollower: kotlin.String,
    @SerialName(value = "dAgo") @Required val dAgo: kotlin.String,
    @SerialName(value = "sAgo") @Required val sAgo: kotlin.String,
    @SerialName(value = "retry") @Required val retry: kotlin.String,
    @SerialName(value = "back") @Required val back: kotlin.String,
    @SerialName(value = "pressBackAgain") @Required val pressBackAgain: kotlin.String,
    @SerialName(value = "picture") @Required val picture: kotlin.String,
    @SerialName(value = "fullSecond") @Required val fullSecond: kotlin.String,
    @SerialName(value = "fullSeconds") @Required val fullSeconds: kotlin.String,
    @SerialName(value = "fullMinute") @Required val fullMinute: kotlin.String,
    @SerialName(value = "fullMinutes") @Required val fullMinutes: kotlin.String,
    @SerialName(value = "fullHour") @Required val fullHour: kotlin.String,
    @SerialName(value = "fullHours") @Required val fullHours: kotlin.String,
    @SerialName(value = "fullDay") @Required val fullDay: kotlin.String,
    @SerialName(value = "fullDays") @Required val fullDays: kotlin.String,
    @SerialName(value = "fullWeek") @Required val fullWeek: kotlin.String,
    @SerialName(value = "fullWeeks") @Required val fullWeeks: kotlin.String,
    @SerialName(value = "byLowercase") @Required val byLowercase: kotlin.String,
    @SerialName(value = "monday") @Required val monday: kotlin.String,
    @SerialName(value = "tuesday") @Required val tuesday: kotlin.String,
    @SerialName(value = "wednesday") @Required val wednesday: kotlin.String,
    @SerialName(value = "thursday") @Required val thursday: kotlin.String,
    @SerialName(value = "friday") @Required val friday: kotlin.String,
    @SerialName(value = "saturday") @Required val saturday: kotlin.String,
    @SerialName(value = "sunday") @Required val sunday: kotlin.String,
    @SerialName(value = "iCurrentlyWorkHere") @Required val iCurrentlyWorkHere: kotlin.String,
    @SerialName(value = "distanceAway") @Required val distanceAway: kotlin.String,
    @SerialName(value = "km") @Required val km: kotlin.String,
    @SerialName(value = "hey") @Required val hey: kotlin.String,
    @SerialName(value = "readMore") @Required val readMore: kotlin.String,
    @SerialName(value = "edit") @Required val edit: kotlin.String,
    @SerialName(value = "save") @Required val save: kotlin.String,
    @SerialName(value = "settings") @Required val settings: kotlin.String,
    @SerialName(value = "later") @Required val later: kotlin.String,
    @SerialName(value = "next") @Required val next: kotlin.String,
    @SerialName(value = "previous") @Required val previous: kotlin.String,
    @SerialName(value = "skip") @Required val skip: kotlin.String,
    @SerialName(value = "zhCN") @Required val zhCN: kotlin.String,
    @SerialName(value = "ptBR") @Required val ptBR: kotlin.String,
    @SerialName(value = "yes") val yes: kotlin.String? = null,
    @SerialName(value = "no") val no: kotlin.String? = null
) 



