/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer
/**
 * 
 * @param natural 
 * @param dagger 
 * @param koi 
 * @param mandala 
 * @param rose 
 * @param hannya 
 */
@Serializable
data class Filters (
    @SerialName(value = "natural") @Required val natural: kotlin.String,
    @SerialName(value = "dagger") @Required val dagger: kotlin.String,
    @SerialName(value = "koi") @Required val koi: kotlin.String,
    @SerialName(value = "mandala") @Required val mandala: kotlin.String,
    @SerialName(value = "rose") @Required val rose: kotlin.String,
    @SerialName(value = "hannya") @Required val hannya: kotlin.String
) 



