/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer
/**
 * 
 * @param breadcrumbsLeftSquareBracket0RightSquareBracketLeftSquareBracketMetaRightSquareBracket 
 * @param os 
 * @param device 
 * @param appVersion 
 * @param name 
 * @param email 
 * @param message 
 * @param image 
 * @param type 
 * @param platform 
 * @param metaLeftSquareBracketKeyRightSquareBracket 
 * @param breadcrumbsLeftSquareBracket0RightSquareBracketLeftSquareBracketEventRightSquareBracket 
 * @param breadcrumbsLeftSquareBracket0RightSquareBracketLeftSquareBracketTimestampRightSquareBracket 
 */
@Serializable
data class InlineObject16 (
    @SerialName(value = "breadcrumbs[0][meta]") @Required val breadcrumbsLeftSquareBracket0RightSquareBracketLeftSquareBracketMetaRightSquareBracket: kotlin.String,
    @SerialName(value = "os") @Required val os: kotlin.String,
    @SerialName(value = "device") @Required val device: kotlin.String,
    @SerialName(value = "app_version") @Required val appVersion: kotlin.String,
    @SerialName(value = "name") @Required val name: kotlin.String,
    @SerialName(value = "email") @Required val email: kotlin.String,
    @SerialName(value = "message") @Required val message: kotlin.String,
    @SerialName(value = "image") @Required val image: kotlin.String,
    @SerialName(value = "type") @Required val type: kotlin.String,
    @SerialName(value = "platform") @Required val platform: kotlin.String,
    @SerialName(value = "meta[key]") @Required val metaLeftSquareBracketKeyRightSquareBracket: kotlin.String,
    @SerialName(value = "breadcrumbs[0][event]") @Required val breadcrumbsLeftSquareBracket0RightSquareBracketLeftSquareBracketEventRightSquareBracket: kotlin.String,
    @SerialName(value = "breadcrumbs[0][timestamp]") @Required val breadcrumbsLeftSquareBracket0RightSquareBracketLeftSquareBracketTimestampRightSquareBracket: kotlin.String
) 



