/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer
/**
 * 
 * @param name 
 * @param tags 
 * @param goneAt 
 * @param file 
 * @param privacy 
 */
@Serializable
data class InlineObject6 (
    @SerialName(value = "name") @Required val name: kotlin.String,
    @SerialName(value = "tags") @Required val tags: kotlin.String,
    @SerialName(value = "gone_at") @Required val goneAt: kotlin.String,
    @SerialName(value = "file") @Required val file: kotlin.String,
    @SerialName(value = "privacy") @Required val privacy: kotlin.String
) 



