/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer
/**
 * 
 * @param k0int 
 * @param key1string 
 * @param key2float 
 * @param key3wysiwygsim 
 * @param key4asset 
 * @param key5boolean 
 * @param key6wysiwygadvanced 
 */
@Serializable
data class InlineObject3 (
    @SerialName(value = "k0int") @Required val k0int: kotlin.Int,
    @SerialName(value = "key1string") @Required val key1string: kotlin.String,
    @SerialName(value = "key2float") @Required val key2float: kotlin.Double,
    @SerialName(value = "key3wysiwygsim") @Required val key3wysiwygsim: kotlin.String,
    @SerialName(value = "key4asset") @Required val key4asset: kotlin.String,
    @SerialName(value = "key5boolean") @Required val key5boolean: kotlin.Boolean,
    @SerialName(value = "key6wysiwygadvanced") @Required val key6wysiwygadvanced: kotlin.String
) 



