/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer
/**
 * 
 * @param title 
 * @param email 
 * @param emailPlaceholder 
 * @param password 
 * @param passwordPlaceholder 
 * @param forgotButton 
 * @param authFailed 
 * @param loginButton 
 * @param yourEmail 
 * @param confirm 
 * @param forgot 
 * @param login 
 * @param invalidTitle 
 * @param invalidBody 
 * @param dontHaveAnAccount 
 */
@Serializable
data class Login (
    @SerialName(value = "title") @Required val title: kotlin.String,
    @SerialName(value = "email") @Required val email: kotlin.String,
    @SerialName(value = "emailPlaceholder") @Required val emailPlaceholder: kotlin.String,
    @SerialName(value = "password") @Required val password: kotlin.String,
    @SerialName(value = "passwordPlaceholder") @Required val passwordPlaceholder: kotlin.String,
    @SerialName(value = "forgotButton") @Required val forgotButton: kotlin.String,
    @SerialName(value = "authFailed") @Required val authFailed: kotlin.String,
    @SerialName(value = "loginButton") @Required val loginButton: kotlin.String,
    @SerialName(value = "yourEmail") @Required val yourEmail: kotlin.String,
    @SerialName(value = "confirm") @Required val confirm: kotlin.String,
    @SerialName(value = "forgot") @Required val forgot: kotlin.String,
    @SerialName(value = "login") @Required val login: kotlin.String,
    @SerialName(value = "invalidTitle") @Required val invalidTitle: kotlin.String,
    @SerialName(value = "invalidBody") @Required val invalidBody: kotlin.String,
    @SerialName(value = "dontHaveAnAccount") @Required val dontHaveAnAccount: kotlin.String
) 



