/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model

import dk.nodes.nstack.kotlin.codegen.model.Translate

import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer
/**
 * 
 * @param state 
 * @param lastId 
 * @param version 
 * @param link 
 * @param translate 
 */
@Serializable
data class NewerVersion (
    @SerialName(value = "state") @Required val state: kotlin.String,
    @SerialName(value = "last_id") @Required val lastId: kotlin.Int,
    @SerialName(value = "version") @Required val version: kotlin.String,
    @SerialName(value = "link") @Required val link: kotlin.String,
    @SerialName(value = "translate") @Required val translate: Translate
) 



