/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer
/**
 * 
 * @param relatedImages 
 * @param showMore 
 * @param doneBy 
 */
@Serializable
data class Post (
    @SerialName(value = "relatedImages") @Required val relatedImages: kotlin.String,
    @SerialName(value = "showMore") @Required val showMore: kotlin.String,
    @SerialName(value = "doneBy") @Required val doneBy: kotlin.String
) 



