/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer
/**
 * 
 * @param signUpWithEmail 
 * @param email 
 * @param password 
 * @param login 
 * @param signUp 
 * @param alreadyHaveAnAccount 
 * @param pleaseEnterValidEmail 
 * @param emailAlreadyTaken 
 * @param passwordTooShort 
 */
@Serializable
data class SignUp (
    @SerialName(value = "signUpWithEmail") @Required val signUpWithEmail: kotlin.String,
    @SerialName(value = "email") @Required val email: kotlin.String,
    @SerialName(value = "password") @Required val password: kotlin.String,
    @SerialName(value = "login") @Required val login: kotlin.String,
    @SerialName(value = "signUp") @Required val signUp: kotlin.String,
    @SerialName(value = "alreadyHaveAnAccount") @Required val alreadyHaveAnAccount: kotlin.String,
    @SerialName(value = "pleaseEnterValidEmail") @Required val pleaseEnterValidEmail: kotlin.String,
    @SerialName(value = "emailAlreadyTaken") @Required val emailAlreadyTaken: kotlin.String,
    @SerialName(value = "passwordTooShort") @Required val passwordTooShort: kotlin.String
) 



