/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer
/**
 * 
 * @param searchTattoos 
 * @param tattoosOfTheDay 
 */
@Serializable
data class Tattoos (
    @SerialName(value = "searchTattoos") @Required val searchTattoos: kotlin.String,
    @SerialName(value = "tattoosOfTheDay") @Required val tattoosOfTheDay: kotlin.String
) 



