/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer
/**
 * 
 * @param deleteLanguageModalText 
 * @param title 
 */
@Serializable
data class TranslateLanguages (
    @SerialName(value = "deleteLanguageModalText") @Required val deleteLanguageModalText: kotlin.String,
    @SerialName(value = "title") @Required val title: kotlin.String
) 



