/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer
/**
 * 
 * @param noLanguageConnection 
 * @param noLanguages 
 * @param noPlatforms 
 * @param platformIsInProduction 
 */
@Serializable
data class TranslateErrors (
    @SerialName(value = "noLanguageConnection") @Required val noLanguageConnection: kotlin.String,
    @SerialName(value = "noLanguages") @Required val noLanguages: kotlin.String,
    @SerialName(value = "noPlatforms") @Required val noPlatforms: kotlin.String,
    @SerialName(value = "platformIsInProduction") @Required val platformIsInProduction: kotlin.String
) 



