/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer
/**
 * 
 * @param addSectionBtn 
 * @param addSectionTitle 
 * @param cacheFlushedSuccess 
 * @param deleteKeyModalText 
 * @param deleteSectionEmptyKeysModelText 
 * @param deleteSectionModalText 
 * @param flushCache 
 * @param updateValueModalTitle 
 */
@Serializable
data class TranslateMain (
    @SerialName(value = "addSectionBtn") @Required val addSectionBtn: kotlin.String,
    @SerialName(value = "addSectionTitle") @Required val addSectionTitle: kotlin.String,
    @SerialName(value = "cacheFlushedSuccess") @Required val cacheFlushedSuccess: kotlin.String,
    @SerialName(value = "deleteKeyModalText") @Required val deleteKeyModalText: kotlin.String,
    @SerialName(value = "deleteSectionEmptyKeysModelText") @Required val deleteSectionEmptyKeysModelText: kotlin.String,
    @SerialName(value = "deleteSectionModalText") @Required val deleteSectionModalText: kotlin.String,
    @SerialName(value = "flushCache") @Required val flushCache: kotlin.String,
    @SerialName(value = "updateValueModalTitle") @Required val updateValueModalTitle: kotlin.String
) 



