/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer
/**
 * 
 * @param firstName 
 * @param lastName 
 */
@Serializable
data class User1 (
    @SerialName(value = "first_name") @Required val firstName: kotlin.String,
    @SerialName(value = "last_name") @Required val lastName: kotlin.String
) 



