/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.api


import org.openapitools.client.infrastructure.*
import io.ktor.client.request.forms.formData
import kotlinx.serialization.UnstableDefault
import io.ktor.client.engine.HttpClientEngine
import io.ktor.client.features.json.serializer.KotlinxSerializer
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonConfiguration
import io.ktor.http.ParametersBuilder
import kotlinx.serialization.*
import kotlinx.serialization.internal.StringDescriptor

class RateRemindersApi @UseExperimental(UnstableDefault::class) constructor(
        baseUrl: kotlin.String = "https://nstack-staging.vapor.cloud",
        httpClientEngine: HttpClientEngine? = null,
        serializer: KotlinxSerializer)
    : ApiClient(baseUrl, httpClientEngine, serializer) {

    @UseExperimental(UnstableDefault::class)
    constructor(
        baseUrl: kotlin.String = "https://nstack-staging.vapor.cloud",
        httpClientEngine: HttpClientEngine? = null,
        jsonConfiguration: JsonConfiguration = JsonConfiguration.Default)
    : this(baseUrl, httpClientEngine, KotlinxSerializer(Json(jsonConfiguration)))

    /**
    * GetShow
    * Get rate reminder  #### Request details Method: &#x60;GET&#x60;  URL: &#x60;/api/v2/notify/rate_reminder&#x60;  #### Headers  &#x60;X-Application-Id&#x60; (string) **required** _Application ID from [NStack](https://nstack.io)_  &#x60;X-Rest-Api-Key&#x60; (string) **required** _Rest API key from [NStack](https://nstack.io)_  #### URL Parameters &#x60;guid&#x60; (int?) **required** _[?]_  &#x60;platform&#x60; (string) **required** _[is this used at all?]_  #### Response codes &#x60;200&#x60; OK  &#x60;412&#x60; Precondition failed  &#x60;445&#x60; Entity not found
    * @param platform  
    * @param guid  
    * @param xminusApplicationMinusId  
    * @param xminusRestMinusApiMinusKey  
    * @return void
    */
    suspend fun getShow(platform: kotlin.String, guid: kotlin.Int, xminusApplicationMinusId: kotlin.String, xminusRestMinusApiMinusKey: kotlin.String) : HttpResponse<Unit> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        platform?.apply { localVariableQuery["platform"] = listOf("$platform") }
        guid?.apply { localVariableQuery["guid"] = listOf("$guid") }

        val localVariableHeaders = mutableMapOf<String, String>()
        xminusApplicationMinusId?.apply { localVariableHeaders["X-Application-Id"] = this.toString() }
        xminusRestMinusApiMinusKey?.apply { localVariableHeaders["X-Rest-Api-Key"] = this.toString() }

        val localVariableConfig = RequestConfig(
            RequestMethod.GET,
            "/api/v2/notify/rate_reminder",
            query = localVariableQuery,
            headers = localVariableHeaders
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
    * GetShow1
    * Get rate reminder  #### Request details Method: &#x60;GET&#x60;  URL: &#x60;/api/v1/notify/rate_reminder&#x60;  #### Headers  &#x60;X-Application-Id&#x60; (string) **required** _Application ID from [NStack](https://nstack.io)_  &#x60;X-Rest-Api-Key&#x60; (string) **required** _Rest API key from [NStack](https://nstack.io)_  #### URL Parameters &#x60;guid&#x60; (int?) **required** _[?]_  &#x60;platform&#x60; (string) **required** _[is this used at all?]_  #### Response codes &#x60;200&#x60; OK  &#x60;412&#x60; Precondition failed  &#x60;445&#x60; Entity not found
    * @param platform  
    * @param guid  
    * @param xminusApplicationMinusId  
    * @param xminusRestMinusApiMinusKey  
    * @return void
    */
    suspend fun getShow1(platform: kotlin.String, guid: kotlin.Int, xminusApplicationMinusId: kotlin.String, xminusRestMinusApiMinusKey: kotlin.String) : HttpResponse<Unit> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        platform?.apply { localVariableQuery["platform"] = listOf("$platform") }
        guid?.apply { localVariableQuery["guid"] = listOf("$guid") }

        val localVariableHeaders = mutableMapOf<String, String>()
        xminusApplicationMinusId?.apply { localVariableHeaders["X-Application-Id"] = this.toString() }
        xminusRestMinusApiMinusKey?.apply { localVariableHeaders["X-Rest-Api-Key"] = this.toString() }

        val localVariableConfig = RequestConfig(
            RequestMethod.GET,
            "/api/v1/notify/rate_reminder",
            query = localVariableQuery,
            headers = localVariableHeaders
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
    * Markasseen1
    * Post rate reminder  #### Request details Method: &#x60;POST&#x60;  URL: &#x60;/api/v1/notify/rate_reminder/views&#x60;  #### Headers  &#x60;X-Application-Id&#x60; (string) **required** _Application ID from [NStack](https://nstack.io)_  &#x60;X-Rest-Api-Key&#x60; (string) **required** _Rest API key from [NStack](https://nstack.io)_  #### URL Parameters &#x60;guid&#x60; (int?) **required** _[?]_  &#x60;platform&#x60; (string) **required** _[is this used at all?]_  &#x60;answer&#x60; (string) **required** _[\&quot;yes\&quot;, \&quot;no\&quot;, \&quot;later\&quot;]_  #### Response codes &#x60;200&#x60; OK  &#x60;412&#x60; Precondition failed  &#x60;445&#x60; Entity not found
    * @param xminusApplicationMinusId  
    * @param xminusRestMinusApiMinusKey  
    * @param guid  
    * @param platform  
    * @param answer  
    * @return void
    */
    suspend fun markasseen1(xminusApplicationMinusId: kotlin.String, xminusRestMinusApiMinusKey: kotlin.String, guid: kotlin.Int, platform: kotlin.String, answer: kotlin.String) : HttpResponse<Unit> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            ParametersBuilder().also {
                guid?.apply { it.append("guid", guid.toString()) }
                platform?.apply { it.append("platform", platform.toString()) }
                answer?.apply { it.append("answer", answer.toString()) }
            }.build()

        val localVariableQuery = mutableMapOf<String, List<String>>()

        val localVariableHeaders = mutableMapOf<String, String>()
        xminusApplicationMinusId?.apply { localVariableHeaders["X-Application-Id"] = this.toString() }
        xminusRestMinusApiMinusKey?.apply { localVariableHeaders["X-Rest-Api-Key"] = this.toString() }

        val localVariableConfig = RequestConfig(
            RequestMethod.POST,
            "/api/v1/notify/rate_reminder/views",
            query = localVariableQuery,
            headers = localVariableHeaders
        )

        return urlEncodedFormRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
    * PostMarkasseen
    * Post rate reminder  #### Request details Method: &#x60;POST&#x60;  URL: &#x60;/api/v2/notify/rate_reminder/views&#x60;  #### Headers  &#x60;X-Application-Id&#x60; (string) **required** _Application ID from [NStack](https://nstack.io)_  &#x60;X-Rest-Api-Key&#x60; (string) **required** _Rest API key from [NStack](https://nstack.io)_  #### URL Parameters &#x60;guid&#x60; (int?) **required** _[?]_  &#x60;platform&#x60; (string) **required** _[is this used at all?]_  &#x60;answer&#x60; (string) **required** _[\&quot;yes\&quot;, \&quot;no\&quot;, \&quot;later\&quot;]_  #### Response codes &#x60;200&#x60; OK  &#x60;412&#x60; Precondition failed  &#x60;445&#x60; Entity not found
    * @param xminusApplicationMinusId  
    * @param xminusRestMinusApiMinusKey  
    * @param guid  
    * @param platform  
    * @param answer  
    * @return void
    */
    suspend fun postMarkasseen(xminusApplicationMinusId: kotlin.String, xminusRestMinusApiMinusKey: kotlin.String, guid: kotlin.Int, platform: kotlin.String, answer: kotlin.String) : HttpResponse<Unit> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            ParametersBuilder().also {
                guid?.apply { it.append("guid", guid.toString()) }
                platform?.apply { it.append("platform", platform.toString()) }
                answer?.apply { it.append("answer", answer.toString()) }
            }.build()

        val localVariableQuery = mutableMapOf<String, List<String>>()

        val localVariableHeaders = mutableMapOf<String, String>()
        xminusApplicationMinusId?.apply { localVariableHeaders["X-Application-Id"] = this.toString() }
        xminusRestMinusApiMinusKey?.apply { localVariableHeaders["X-Rest-Api-Key"] = this.toString() }

        val localVariableConfig = RequestConfig(
            RequestMethod.POST,
            "/api/v2/notify/rate_reminder/views",
            query = localVariableQuery,
            headers = localVariableHeaders
        )

        return urlEncodedFormRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    companion object {
        internal fun setMappers(serializer: KotlinxSerializer) {
        }
    }
}
