/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package dk.nodes.nstack.kotlin.codegen.apis

import okhttp3.RequestBody

import dk.nodes.nstack.kotlin.codegen.models.AppopenV2
import io.reactivex.Single
import retrofit2.http.GET
import retrofit2.http.Headers

@JvmSuppressWildcards
interface AdminAPIApi {
  /** 
   * Search
   * Retrieve a list of valid continents on Earth  #### Request details Method:    `GET`  URL:    `/admin/search/company-applications`  #### Headers  `Authorization` (string) **required** _Token_  #### Response codes(s) `200` OK
   * The endpoint is owned by NStack v2 service owner
   * @param q  (required)
   * @param authorization  (required)
   */
  @Headers(
    "X-Operation-Id: Search",
    "Content-Type: application/json"
  )
  @GET("admin/search/company-applications")
  fun search(
    @retrofit2.http.Query("q") q: String,
    @retrofit2.http.Header("Authorization") authorization: String
  ): Single<AppopenV2>

}
