/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package dk.nodes.nstack.kotlin.codegen.apis

import okhttp3.RequestBody

import io.reactivex.Completable
import retrofit2.http.GET
import retrofit2.http.Headers

@JvmSuppressWildcards
interface ContinentsApi {
  /** 
   * Index
   * Retrieve a list of valid continents on Earth  #### Request details Method:    `GET`  URL:    `/api/v2/geographic/continents`  #### Headers  `X-Application-Id` (string) **required** _Application ID from [NStack](https://nstack.io)_  `X-Rest-Api-Key` (string) **required** _Rest API key from [NStack](https://nstack.io)_  #### Response codes(s) `200` OK
   * The endpoint is owned by NStack v2 service owner
   */
  @Headers(
    "X-Operation-Id: GetIndex",
    "Content-Type: application/json"
  )
  @GET("api/v2/geographic/continents")
  fun getIndex()
    : Completable

  /** 
   * Show
   * Retrieve a list of valid continents on Earth  #### Request details Method:    `GET`  URL:    `/api/v2/geographic/continents/{id}`  #### Headers  `X-Application-Id` (string) **required** _Application ID from [NStack](https://nstack.io)_  `X-Rest-Api-Key` (string) **required** _Rest API key from [NStack](https://nstack.io)_  #### Response codes(s) `200` OK  `404` Not found
   * The endpoint is owned by NStack v2 service owner
   */
  @Headers(
    "X-Operation-Id: GetShow123",
    "Content-Type: application/json"
  )
  @GET("api/v2/geographic/continents/1")
  fun getShow123()
    : Completable

  /** 
   * Index1
   * Retrieve a list of valid continents on Earth  #### Request details Method:    `GET`  URL:    `/api/v1/geographic/continents`  #### Headers  `X-Application-Id` (string) **required** _Application ID from [NStack](https://nstack.io)_  `X-Rest-Api-Key` (string) **required** _Rest API key from [NStack](https://nstack.io)_  #### Response codes(s) `200` OK
   * The endpoint is owned by NStack v2 service owner
   */
  @Headers(
    "X-Operation-Id: Index1",
    "Content-Type: application/json"
  )
  @GET("api/v1/geographic/continents")
  fun index1()
    : Completable

}
