/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package dk.nodes.nstack.kotlin.codegen.models

import com.squareup.moshi.Json

/**
 * 
 * @property yourContent 
 * @property following 
 * @property myActivity 
 * @property title 
 * @property typeLike 
 * @property typeComment 
 * @property typePost 
 * @property typeMention 
 * @property titleError 
 * @property youLiked 
 * @property someonesPhoto 
 * @property liked 
 * @property youCommented 
 * @property commentedOnArticle 
 * @property likedAArticle 
 * @property you 
 * @property commentedOn 
 * @property yourPhoto 
 * @property youMentioned 
 * @property yourself 
 * @property mentioned 
 * @property noActivity 
 * @property typeArticle 
 * @property youFollow 
 * @property isFollowing 
 * @property aPhoto 
 * @property anArticle 
 * @property someonesArticle 
 * @property typeArticleLike 
 * @property typeArticleComment 
 * @property aComment 
 * @property someonesComment 
 * @property yourArticle 
 * @property yourComment 
 * @property youUnfollowed 
 * @property youFollowed 
 * @property followed 
 * @property unfollowed 
 * @property someone 
 * @property inSomething 
 * @property deny 
 * @property approve 
 * @property wantsToAddYou 
 */
data class Activity (
        @Json(name = "yourContent") @field:Json(name = "yourContent") var yourContent: String,
        @Json(name = "following") @field:Json(name = "following") var following: String,
        @Json(name = "myActivity") @field:Json(name = "myActivity") var myActivity: String,
        @Json(name = "title") @field:Json(name = "title") var title: String,
        @Json(name = "typeLike") @field:Json(name = "typeLike") var typeLike: String,
        @Json(name = "typeComment") @field:Json(name = "typeComment") var typeComment: String,
        @Json(name = "typePost") @field:Json(name = "typePost") var typePost: String,
        @Json(name = "typeMention") @field:Json(name = "typeMention") var typeMention: String,
        @Json(name = "titleError") @field:Json(name = "titleError") var titleError: String,
        @Json(name = "youLiked") @field:Json(name = "youLiked") var youLiked: String,
        @Json(name = "someonesPhoto") @field:Json(name = "someonesPhoto") var someonesPhoto: String,
        @Json(name = "liked") @field:Json(name = "liked") var liked: String,
        @Json(name = "youCommented") @field:Json(name = "youCommented") var youCommented: String,
        @Json(name = "commentedOnArticle") @field:Json(name = "commentedOnArticle") var commentedOnArticle: String,
        @Json(name = "likedAArticle") @field:Json(name = "likedAArticle") var likedAArticle: String,
        @Json(name = "you") @field:Json(name = "you") var you: String,
        @Json(name = "commentedOn") @field:Json(name = "commentedOn") var commentedOn: String,
        @Json(name = "yourPhoto") @field:Json(name = "yourPhoto") var yourPhoto: String,
        @Json(name = "youMentioned") @field:Json(name = "youMentioned") var youMentioned: String,
        @Json(name = "yourself") @field:Json(name = "yourself") var yourself: String,
        @Json(name = "mentioned") @field:Json(name = "mentioned") var mentioned: String,
        @Json(name = "noActivity") @field:Json(name = "noActivity") var noActivity: String,
        @Json(name = "typeArticle") @field:Json(name = "typeArticle") var typeArticle: String,
        @Json(name = "youFollow") @field:Json(name = "youFollow") var youFollow: String,
        @Json(name = "isFollowing") @field:Json(name = "isFollowing") var isFollowing: String,
        @Json(name = "aPhoto") @field:Json(name = "aPhoto") var aPhoto: String,
        @Json(name = "anArticle") @field:Json(name = "anArticle") var anArticle: String,
        @Json(name = "someonesArticle") @field:Json(name = "someonesArticle") var someonesArticle: String,
        @Json(name = "typeArticleLike") @field:Json(name = "typeArticleLike") var typeArticleLike: String,
        @Json(name = "typeArticleComment") @field:Json(name = "typeArticleComment") var typeArticleComment: String,
        @Json(name = "aComment") @field:Json(name = "aComment") var aComment: String,
        @Json(name = "someonesComment") @field:Json(name = "someonesComment") var someonesComment: String,
        @Json(name = "yourArticle") @field:Json(name = "yourArticle") var yourArticle: String,
        @Json(name = "yourComment") @field:Json(name = "yourComment") var yourComment: String,
        @Json(name = "youUnfollowed") @field:Json(name = "youUnfollowed") var youUnfollowed: String,
        @Json(name = "youFollowed") @field:Json(name = "youFollowed") var youFollowed: String,
        @Json(name = "followed") @field:Json(name = "followed") var followed: String,
        @Json(name = "unfollowed") @field:Json(name = "unfollowed") var unfollowed: String,
        @Json(name = "someone") @field:Json(name = "someone") var someone: String,
        @Json(name = "inSomething") @field:Json(name = "inSomething") var inSomething: String,
        @Json(name = "deny") @field:Json(name = "deny") var deny: String,
        @Json(name = "approve") @field:Json(name = "approve") var approve: String,
        @Json(name = "wantsToAddYou") @field:Json(name = "wantsToAddYou") var wantsToAddYou: String
)

