/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package dk.nodes.nstack.kotlin.codegen.models

import com.squareup.moshi.Json

/**
 * 
 * @property guid 
 * @property answer 
 */
data class AnswerRequest (
        @Json(name = "guid") @field:Json(name = "guid") var guid: String,
        @Json(name = "answer") @field:Json(name = "answer") var answer: String
)

