/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package dk.nodes.nstack.kotlin.codegen.models

import com.squareup.moshi.Json

/**
 * 
 * @property title 
 * @property none 
 * @property arms 
 * @property legs 
 * @property torso 
 * @property head 
 * @property left 
 * @property right 
 */
data class BodyPart (
        @Json(name = "title") @field:Json(name = "title") var title: String,
        @Json(name = "none") @field:Json(name = "none") var none: String,
        @Json(name = "arms") @field:Json(name = "arms") var arms: String,
        @Json(name = "legs") @field:Json(name = "legs") var legs: String,
        @Json(name = "torso") @field:Json(name = "torso") var torso: String,
        @Json(name = "head") @field:Json(name = "head") var head: String,
        @Json(name = "left") @field:Json(name = "left") var left: String,
        @Json(name = "right") @field:Json(name = "right") var right: String
)

