/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package dk.nodes.nstack.kotlin.codegen.models

import com.squareup.moshi.Json

/**
 * 
 * @property notifications 
 * @property deny 
 * @property accept 
 * @property wantsToAddYou 
 * @property noNotifications 
 * @property noNotificationsSubtitle 
 * @property commentPost 
 * @property likePost 
 * @property mentionInComment 
 * @property followingYou 
 * @property pinPost 
 * @property mentionInPost 
 * @property mentionInArticle 
 * @property shopReviewResponse 
 * @property acceptingInvitation 
 */
data class Communication (
        @Json(name = "notifications") @field:Json(name = "notifications") var notifications: String,
        @Json(name = "deny") @field:Json(name = "deny") var deny: String,
        @Json(name = "accept") @field:Json(name = "accept") var accept: String,
        @Json(name = "wantsToAddYou") @field:Json(name = "wantsToAddYou") var wantsToAddYou: String,
        @Json(name = "noNotifications") @field:Json(name = "noNotifications") var noNotifications: String,
        @Json(name = "noNotificationsSubtitle") @field:Json(name = "noNotificationsSubtitle") var noNotificationsSubtitle: String,
        @Json(name = "commentPost") @field:Json(name = "commentPost") var commentPost: String,
        @Json(name = "likePost") @field:Json(name = "likePost") var likePost: String,
        @Json(name = "mentionInComment") @field:Json(name = "mentionInComment") var mentionInComment: String,
        @Json(name = "followingYou") @field:Json(name = "followingYou") var followingYou: String,
        @Json(name = "pinPost") @field:Json(name = "pinPost") var pinPost: String,
        @Json(name = "mentionInPost") @field:Json(name = "mentionInPost") var mentionInPost: String,
        @Json(name = "mentionInArticle") @field:Json(name = "mentionInArticle") var mentionInArticle: String,
        @Json(name = "shopReviewResponse") @field:Json(name = "shopReviewResponse") var shopReviewResponse: String,
        @Json(name = "acceptingInvitation") @field:Json(name = "acceptingInvitation") var acceptingInvitation: String
)

