/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package dk.nodes.nstack.kotlin.codegen.models

import com.squareup.moshi.Json

/**
 * 
 * @property library 
 * @property capture 
 * @property choosePhotoTitle 
 * @property takePhotoTitle 
 * @property nextButton 
 * @property noCameraTitle 
 * @property noCameraMessage 
 * @property noImages 
 * @property errorBodyPartNoneAndMyBodyChecked 
 * @property addArtist 
 * @property addShop 
 * @property addClient 
 * @property me 
 * @property addToBoard 
 * @property submitLabel 
 * @property searchArtist 
 * @property searchShop 
 * @property searchClient 
 * @property addDescription 
 * @property uploadNow 
 * @property createPostError 
 */
data class CreateNewPost (
        @Json(name = "library") @field:Json(name = "library") var library: String,
        @Json(name = "capture") @field:Json(name = "capture") var capture: String,
        @Json(name = "choosePhotoTitle") @field:Json(name = "choosePhotoTitle") var choosePhotoTitle: String,
        @Json(name = "takePhotoTitle") @field:Json(name = "takePhotoTitle") var takePhotoTitle: String,
        @Json(name = "nextButton") @field:Json(name = "nextButton") var nextButton: String,
        @Json(name = "noCameraTitle") @field:Json(name = "noCameraTitle") var noCameraTitle: String,
        @Json(name = "noCameraMessage") @field:Json(name = "noCameraMessage") var noCameraMessage: String,
        @Json(name = "noImages") @field:Json(name = "noImages") var noImages: String,
        @Json(name = "errorBodyPartNoneAndMyBodyChecked") @field:Json(name = "errorBodyPartNoneAndMyBodyChecked") var errorBodyPartNoneAndMyBodyChecked: String,
        @Json(name = "addArtist") @field:Json(name = "addArtist") var addArtist: String,
        @Json(name = "addShop") @field:Json(name = "addShop") var addShop: String,
        @Json(name = "addClient") @field:Json(name = "addClient") var addClient: String,
        @Json(name = "me") @field:Json(name = "me") var me: String,
        @Json(name = "addToBoard") @field:Json(name = "addToBoard") var addToBoard: String,
        @Json(name = "submitLabel") @field:Json(name = "submitLabel") var submitLabel: String,
        @Json(name = "searchArtist") @field:Json(name = "searchArtist") var searchArtist: String,
        @Json(name = "searchShop") @field:Json(name = "searchShop") var searchShop: String,
        @Json(name = "searchClient") @field:Json(name = "searchClient") var searchClient: String,
        @Json(name = "addDescription") @field:Json(name = "addDescription") var addDescription: String,
        @Json(name = "uploadNow") @field:Json(name = "uploadNow") var uploadNow: String,
        @Json(name = "createPostError") @field:Json(name = "createPostError") var createPostError: String
)

