/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package dk.nodes.nstack.kotlin.codegen.models

import com.squareup.moshi.Json

/**
 * 
 * @property id 
 * @property url 
 * @property lastUpdatedAt 
 * @property shouldUpdate 
 * @property language 
 */
data class Data1 (
        @Json(name = "id") @field:Json(name = "id") var id: Int,
        @Json(name = "url") @field:Json(name = "url") var url: String,
        @Json(name = "last_updated_at") @field:Json(name = "last_updated_at") var lastUpdatedAt: String,
        @Json(name = "should_update") @field:Json(name = "should_update") var shouldUpdate: Boolean,
        @Json(name = "language") @field:Json(name = "language") var language: Language
)

