/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package dk.nodes.nstack.kotlin.codegen.models

import com.squareup.moshi.Json

/**
 * 
 * @property default 
 * @property translatePlatforms 
 * @property translateDefault 
 * @property errors 
 * @property translateErrors 
 * @property translateLanguages 
 * @property translatePlatformLanguages 
 * @property translateMain 
 * @property translateImport 
 */
data class Data6 (
        @Json(name = "default") @field:Json(name = "default") var default: Default1,
        @Json(name = "translate_platforms") @field:Json(name = "translate_platforms") var translatePlatforms: TranslatePlatforms,
        @Json(name = "translate_default") @field:Json(name = "translate_default") var translateDefault: TranslateDefault,
        @Json(name = "errors") @field:Json(name = "errors") var errors: Errors1,
        @Json(name = "translate_errors") @field:Json(name = "translate_errors") var translateErrors: TranslateErrors,
        @Json(name = "translate_languages") @field:Json(name = "translate_languages") var translateLanguages: TranslateLanguages,
        @Json(name = "translate_platform_languages") @field:Json(name = "translate_platform_languages") var translatePlatformLanguages: TranslatePlatformLanguages,
        @Json(name = "translate_main") @field:Json(name = "translate_main") var translateMain: TranslateMain,
        @Json(name = "translate_import") @field:Json(name = "translate_import") var translateImport: TranslateImport
)

