/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package dk.nodes.nstack.kotlin.codegen.models

import com.squareup.moshi.Json

/**
 * 
 * @property count 
 * @property update 
 * @property localize 
 * @property platform 
 * @property createdAt 
 * @property lastUpdated 
 */
data class Data4 (
        @Json(name = "count") @field:Json(name = "count") var count: Int,
        @Json(name = "update") @field:Json(name = "update") var update: Update,
        @Json(name = "localize") @field:Json(name = "localize") var localize: List<Localize>,
        @Json(name = "platform") @field:Json(name = "platform") var platform: String,
        @Json(name = "created_at") @field:Json(name = "created_at") var createdAt: String,
        @Json(name = "last_updated") @field:Json(name = "last_updated") var lastUpdated: String
)

