/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package dk.nodes.nstack.kotlin.codegen.models

import com.squareup.moshi.Json

/**
 * 
 * @property ok 
 * @property required 
 * @property cancel 
 * @property done 
 * @property male 
 * @property female 
 * @property errorRandomErrorAlertText 
 * @property ago 
 * @property now 
 * @property `open` 
 * @property openLinkTitle 
 * @property openLinkMessage 
 * @property justNow 
 * @property aMinuteAgo 
 * @property anHourAgo 
 * @property hoursAgo 
 * @property yesterday 
 * @property week 
 * @property weeks 
 * @property month 
 * @property months 
 * @property minutesAgo 
 * @property youGotANewFollower 
 * @property dAgo 
 * @property sAgo 
 * @property yes 
 * @property no 
 * @property retry 
 * @property back 
 * @property pressBackAgain 
 * @property picture 
 * @property fullSecond 
 * @property fullSeconds 
 * @property fullMinute 
 * @property fullMinutes 
 * @property fullHour 
 * @property fullHours 
 * @property fullDay 
 * @property fullDays 
 * @property fullWeek 
 * @property fullWeeks 
 * @property byLowercase 
 * @property monday 
 * @property tuesday 
 * @property wednesday 
 * @property thursday 
 * @property friday 
 * @property saturday 
 * @property sunday 
 * @property iCurrentlyWorkHere 
 * @property distanceAway 
 * @property km 
 * @property hey 
 * @property readMore 
 * @property edit 
 * @property save 
 * @property settings 
 * @property later 
 * @property next 
 * @property previous 
 * @property skip 
 * @property zhCN 
 * @property ptBR 
 */
data class Default (
        @Json(name = "ok") @field:Json(name = "ok") var ok: String,
        @Json(name = "required") @field:Json(name = "required") var required: String,
        @Json(name = "cancel") @field:Json(name = "cancel") var cancel: String,
        @Json(name = "done") @field:Json(name = "done") var done: String,
        @Json(name = "male") @field:Json(name = "male") var male: String,
        @Json(name = "female") @field:Json(name = "female") var female: String,
        @Json(name = "errorRandomErrorAlertText") @field:Json(name = "errorRandomErrorAlertText") var errorRandomErrorAlertText: String,
        @Json(name = "ago") @field:Json(name = "ago") var ago: String,
        @Json(name = "now") @field:Json(name = "now") var now: String,
        @Json(name = "open") @field:Json(name = "open") var `open`: String,
        @Json(name = "openLinkTitle") @field:Json(name = "openLinkTitle") var openLinkTitle: String,
        @Json(name = "openLinkMessage") @field:Json(name = "openLinkMessage") var openLinkMessage: String,
        @Json(name = "justNow") @field:Json(name = "justNow") var justNow: String,
        @Json(name = "aMinuteAgo") @field:Json(name = "aMinuteAgo") var aMinuteAgo: String,
        @Json(name = "anHourAgo") @field:Json(name = "anHourAgo") var anHourAgo: String,
        @Json(name = "hoursAgo") @field:Json(name = "hoursAgo") var hoursAgo: String,
        @Json(name = "yesterday") @field:Json(name = "yesterday") var yesterday: String,
        @Json(name = "week") @field:Json(name = "week") var week: String,
        @Json(name = "weeks") @field:Json(name = "weeks") var weeks: String,
        @Json(name = "month") @field:Json(name = "month") var month: String,
        @Json(name = "months") @field:Json(name = "months") var months: String,
        @Json(name = "minutesAgo") @field:Json(name = "minutesAgo") var minutesAgo: String,
        @Json(name = "youGotANewFollower") @field:Json(name = "youGotANewFollower") var youGotANewFollower: String,
        @Json(name = "dAgo") @field:Json(name = "dAgo") var dAgo: String,
        @Json(name = "sAgo") @field:Json(name = "sAgo") var sAgo: String,
        @Json(name = "yes") @field:Json(name = "yes") var yes: String,
        @Json(name = "no") @field:Json(name = "no") var no: String,
        @Json(name = "retry") @field:Json(name = "retry") var retry: String,
        @Json(name = "back") @field:Json(name = "back") var back: String,
        @Json(name = "pressBackAgain") @field:Json(name = "pressBackAgain") var pressBackAgain: String,
        @Json(name = "picture") @field:Json(name = "picture") var picture: String,
        @Json(name = "fullSecond") @field:Json(name = "fullSecond") var fullSecond: String,
        @Json(name = "fullSeconds") @field:Json(name = "fullSeconds") var fullSeconds: String,
        @Json(name = "fullMinute") @field:Json(name = "fullMinute") var fullMinute: String,
        @Json(name = "fullMinutes") @field:Json(name = "fullMinutes") var fullMinutes: String,
        @Json(name = "fullHour") @field:Json(name = "fullHour") var fullHour: String,
        @Json(name = "fullHours") @field:Json(name = "fullHours") var fullHours: String,
        @Json(name = "fullDay") @field:Json(name = "fullDay") var fullDay: String,
        @Json(name = "fullDays") @field:Json(name = "fullDays") var fullDays: String,
        @Json(name = "fullWeek") @field:Json(name = "fullWeek") var fullWeek: String,
        @Json(name = "fullWeeks") @field:Json(name = "fullWeeks") var fullWeeks: String,
        @Json(name = "byLowercase") @field:Json(name = "byLowercase") var byLowercase: String,
        @Json(name = "monday") @field:Json(name = "monday") var monday: String,
        @Json(name = "tuesday") @field:Json(name = "tuesday") var tuesday: String,
        @Json(name = "wednesday") @field:Json(name = "wednesday") var wednesday: String,
        @Json(name = "thursday") @field:Json(name = "thursday") var thursday: String,
        @Json(name = "friday") @field:Json(name = "friday") var friday: String,
        @Json(name = "saturday") @field:Json(name = "saturday") var saturday: String,
        @Json(name = "sunday") @field:Json(name = "sunday") var sunday: String,
        @Json(name = "iCurrentlyWorkHere") @field:Json(name = "iCurrentlyWorkHere") var iCurrentlyWorkHere: String,
        @Json(name = "distanceAway") @field:Json(name = "distanceAway") var distanceAway: String,
        @Json(name = "km") @field:Json(name = "km") var km: String,
        @Json(name = "hey") @field:Json(name = "hey") var hey: String,
        @Json(name = "readMore") @field:Json(name = "readMore") var readMore: String,
        @Json(name = "edit") @field:Json(name = "edit") var edit: String,
        @Json(name = "save") @field:Json(name = "save") var save: String,
        @Json(name = "settings") @field:Json(name = "settings") var settings: String,
        @Json(name = "later") @field:Json(name = "later") var later: String,
        @Json(name = "next") @field:Json(name = "next") var next: String,
        @Json(name = "previous") @field:Json(name = "previous") var previous: String,
        @Json(name = "skip") @field:Json(name = "skip") var skip: String,
        @Json(name = "zhCN") @field:Json(name = "zhCN") var zhCN: String,
        @Json(name = "ptBR") @field:Json(name = "ptBR") var ptBR: String
)

