/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package dk.nodes.nstack.kotlin.codegen.models

import com.squareup.moshi.Json

/**
 * 
 * @property username 
 * @property email 
 * @property name 
 * @property biography 
 * @property photoChange 
 * @property save 
 * @property changePassword 
 * @property gender 
 * @property genderMale 
 * @property genderFemale 
 * @property birthday 
 * @property title 
 * @property photoTake 
 * @property photoSelect 
 * @property photoRemove 
 * @property namePlaceholder 
 * @property biographyPlaceholder 
 * @property choose 
 * @property genderNotSpecified 
 * @property photoAdd 
 * @property imagePlaceholder 
 * @property genderAlertMessage 
 * @property required 
 * @property editSuccess 
 * @property photoRemovePlain 
 * @property removeImageTitle 
 * @property removeImageMessage 
 * @property removeImagePositiveBtn 
 * @property countryList 
 * @property changeProfileImage 
 * @property removeImageNegativeBtn 
 */
data class EditProfile (
        @Json(name = "username") @field:Json(name = "username") var username: String,
        @Json(name = "email") @field:Json(name = "email") var email: String,
        @Json(name = "name") @field:Json(name = "name") var name: String,
        @Json(name = "biography") @field:Json(name = "biography") var biography: String,
        @Json(name = "photoChange") @field:Json(name = "photoChange") var photoChange: String,
        @Json(name = "save") @field:Json(name = "save") var save: String,
        @Json(name = "changePassword") @field:Json(name = "changePassword") var changePassword: String,
        @Json(name = "gender") @field:Json(name = "gender") var gender: String,
        @Json(name = "genderMale") @field:Json(name = "genderMale") var genderMale: String,
        @Json(name = "genderFemale") @field:Json(name = "genderFemale") var genderFemale: String,
        @Json(name = "birthday") @field:Json(name = "birthday") var birthday: String,
        @Json(name = "title") @field:Json(name = "title") var title: String,
        @Json(name = "photoTake") @field:Json(name = "photoTake") var photoTake: String,
        @Json(name = "photoSelect") @field:Json(name = "photoSelect") var photoSelect: String,
        @Json(name = "photoRemove") @field:Json(name = "photoRemove") var photoRemove: String,
        @Json(name = "namePlaceholder") @field:Json(name = "namePlaceholder") var namePlaceholder: String,
        @Json(name = "biographyPlaceholder") @field:Json(name = "biographyPlaceholder") var biographyPlaceholder: String,
        @Json(name = "choose") @field:Json(name = "choose") var choose: String,
        @Json(name = "genderNotSpecified") @field:Json(name = "genderNotSpecified") var genderNotSpecified: String,
        @Json(name = "photoAdd") @field:Json(name = "photoAdd") var photoAdd: String,
        @Json(name = "imagePlaceholder") @field:Json(name = "imagePlaceholder") var imagePlaceholder: String,
        @Json(name = "genderAlertMessage") @field:Json(name = "genderAlertMessage") var genderAlertMessage: String,
        @Json(name = "required") @field:Json(name = "required") var required: String,
        @Json(name = "editSuccess") @field:Json(name = "editSuccess") var editSuccess: String,
        @Json(name = "photoRemovePlain") @field:Json(name = "photoRemovePlain") var photoRemovePlain: String,
        @Json(name = "removeImageTitle") @field:Json(name = "removeImageTitle") var removeImageTitle: String,
        @Json(name = "removeImageMessage") @field:Json(name = "removeImageMessage") var removeImageMessage: String,
        @Json(name = "removeImagePositiveBtn") @field:Json(name = "removeImagePositiveBtn") var removeImagePositiveBtn: String,
        @Json(name = "countryList") @field:Json(name = "countryList") var countryList: String,
        @Json(name = "changeProfileImage") @field:Json(name = "changeProfileImage") var changeProfileImage: String,
        @Json(name = "removeImageNegativeBtn") @field:Json(name = "removeImageNegativeBtn") var removeImageNegativeBtn: String
)

