/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package dk.nodes.nstack.kotlin.codegen.models

import com.squareup.moshi.Json

/**
 * 
 * @property filters 
 * @property reset 
 * @property title 
 * @property imageErrorMessage 
 */
data class EditImage (
        @Json(name = "filters") @field:Json(name = "filters") var filters: String,
        @Json(name = "reset") @field:Json(name = "reset") var reset: String,
        @Json(name = "title") @field:Json(name = "title") var title: String,
        @Json(name = "imageErrorMessage") @field:Json(name = "imageErrorMessage") var imageErrorMessage: String
)

