/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package dk.nodes.nstack.kotlin.codegen.models

import com.squareup.moshi.Json

/**
 * 
 * @property invalidOrMissingFields 
 * @property emailAlreadyInUse 
 * @property title 
 * @property facebookTokenVerificationFailed 
 * @property twitterTokenVerificationFailed 
 * @property unknownError 
 * @property incorrectPassword 
 * @property newPasswordTooShort 
 * @property loginNeeded 
 * @property loginButton 
 * @property loginNeededTitle 
 * @property connectionErrorTitle 
 * @property connectionError 
 * @property tryAgain 
 * @property cancel 
 * @property giveCameraAccessText 
 * @property giveLibraryAccessText 
 * @property giveAccessButton 
 * @property noCameraAccessText 
 * @property openSettingsButton 
 * @property noLibraryAccessText 
 * @property canNotSendEmailMessage 
 * @property invalidToken 
 * @property couldntFindUser 
 * @property tokenExpired 
 * @property invalidAcceptHeader 
 * @property couldntFindEntity 
 * @property twitterLoginErrorTitle 
 * @property couldntFindImage 
 * @property invalidTokenTitle 
 * @property noCameraAccessTextAndroid 
 * @property noLibraryAccessTextAndroid 
 * @property cameraConnectionError 
 * @property loginCanceledTitle 
 * @property loginCanceledMessage 
 * @property loginFailedTitle 
 * @property loginFailedMessage 
 * @property shopsCannotPinPosts 
 * @property invalidImage 
 * @property invalidShopName 
 * @property fieldRequired 
 * @property passwordErrorCharacter 
 * @property passwordErrorTooShort 
 * @property passwordErrorIncorrect 
 * @property invalidImageTitle 
 * @property failedToLoadContent 
 * @property checkIfYouHaveAnInternetConnection 
 * @property pullToRefresh 
 * @property noCameraPermissionTitle 
 * @property noCameraPermissionMessage 
 */
data class Errors (
        @Json(name = "invalidOrMissingFields") @field:Json(name = "invalidOrMissingFields") var invalidOrMissingFields: String,
        @Json(name = "emailAlreadyInUse") @field:Json(name = "emailAlreadyInUse") var emailAlreadyInUse: String,
        @Json(name = "title") @field:Json(name = "title") var title: String,
        @Json(name = "facebookTokenVerificationFailed") @field:Json(name = "facebookTokenVerificationFailed") var facebookTokenVerificationFailed: String,
        @Json(name = "twitterTokenVerificationFailed") @field:Json(name = "twitterTokenVerificationFailed") var twitterTokenVerificationFailed: String,
        @Json(name = "unknownError") @field:Json(name = "unknownError") var unknownError: String,
        @Json(name = "incorrectPassword") @field:Json(name = "incorrectPassword") var incorrectPassword: String,
        @Json(name = "newPasswordTooShort") @field:Json(name = "newPasswordTooShort") var newPasswordTooShort: String,
        @Json(name = "loginNeeded") @field:Json(name = "loginNeeded") var loginNeeded: String,
        @Json(name = "loginButton") @field:Json(name = "loginButton") var loginButton: String,
        @Json(name = "loginNeededTitle") @field:Json(name = "loginNeededTitle") var loginNeededTitle: String,
        @Json(name = "connectionErrorTitle") @field:Json(name = "connectionErrorTitle") var connectionErrorTitle: String,
        @Json(name = "connectionError") @field:Json(name = "connectionError") var connectionError: String,
        @Json(name = "tryAgain") @field:Json(name = "tryAgain") var tryAgain: String,
        @Json(name = "cancel") @field:Json(name = "cancel") var cancel: String,
        @Json(name = "giveCameraAccessText") @field:Json(name = "giveCameraAccessText") var giveCameraAccessText: String,
        @Json(name = "giveLibraryAccessText") @field:Json(name = "giveLibraryAccessText") var giveLibraryAccessText: String,
        @Json(name = "giveAccessButton") @field:Json(name = "giveAccessButton") var giveAccessButton: String,
        @Json(name = "noCameraAccessText") @field:Json(name = "noCameraAccessText") var noCameraAccessText: String,
        @Json(name = "openSettingsButton") @field:Json(name = "openSettingsButton") var openSettingsButton: String,
        @Json(name = "noLibraryAccessText") @field:Json(name = "noLibraryAccessText") var noLibraryAccessText: String,
        @Json(name = "canNotSendEmailMessage") @field:Json(name = "canNotSendEmailMessage") var canNotSendEmailMessage: String,
        @Json(name = "invalidToken") @field:Json(name = "invalidToken") var invalidToken: String,
        @Json(name = "couldntFindUser") @field:Json(name = "couldntFindUser") var couldntFindUser: String,
        @Json(name = "tokenExpired") @field:Json(name = "tokenExpired") var tokenExpired: String,
        @Json(name = "invalidAcceptHeader") @field:Json(name = "invalidAcceptHeader") var invalidAcceptHeader: String,
        @Json(name = "couldntFindEntity") @field:Json(name = "couldntFindEntity") var couldntFindEntity: String,
        @Json(name = "twitterLoginErrorTitle") @field:Json(name = "twitterLoginErrorTitle") var twitterLoginErrorTitle: String,
        @Json(name = "couldntFindImage") @field:Json(name = "couldntFindImage") var couldntFindImage: String,
        @Json(name = "invalidTokenTitle") @field:Json(name = "invalidTokenTitle") var invalidTokenTitle: String,
        @Json(name = "noCameraAccessTextAndroid") @field:Json(name = "noCameraAccessTextAndroid") var noCameraAccessTextAndroid: String,
        @Json(name = "noLibraryAccessTextAndroid") @field:Json(name = "noLibraryAccessTextAndroid") var noLibraryAccessTextAndroid: String,
        @Json(name = "cameraConnectionError") @field:Json(name = "cameraConnectionError") var cameraConnectionError: String,
        @Json(name = "loginCanceledTitle") @field:Json(name = "loginCanceledTitle") var loginCanceledTitle: String,
        @Json(name = "loginCanceledMessage") @field:Json(name = "loginCanceledMessage") var loginCanceledMessage: String,
        @Json(name = "loginFailedTitle") @field:Json(name = "loginFailedTitle") var loginFailedTitle: String,
        @Json(name = "loginFailedMessage") @field:Json(name = "loginFailedMessage") var loginFailedMessage: String,
        @Json(name = "shopsCannotPinPosts") @field:Json(name = "shopsCannotPinPosts") var shopsCannotPinPosts: String,
        @Json(name = "invalidImage") @field:Json(name = "invalidImage") var invalidImage: String,
        @Json(name = "invalidShopName") @field:Json(name = "invalidShopName") var invalidShopName: String,
        @Json(name = "fieldRequired") @field:Json(name = "fieldRequired") var fieldRequired: String,
        @Json(name = "passwordErrorCharacter") @field:Json(name = "passwordErrorCharacter") var passwordErrorCharacter: String,
        @Json(name = "passwordErrorTooShort") @field:Json(name = "passwordErrorTooShort") var passwordErrorTooShort: String,
        @Json(name = "passwordErrorIncorrect") @field:Json(name = "passwordErrorIncorrect") var passwordErrorIncorrect: String,
        @Json(name = "invalidImageTitle") @field:Json(name = "invalidImageTitle") var invalidImageTitle: String,
        @Json(name = "failedToLoadContent") @field:Json(name = "failedToLoadContent") var failedToLoadContent: String,
        @Json(name = "checkIfYouHaveAnInternetConnection") @field:Json(name = "checkIfYouHaveAnInternetConnection") var checkIfYouHaveAnInternetConnection: String,
        @Json(name = "pullToRefresh") @field:Json(name = "pullToRefresh") var pullToRefresh: String,
        @Json(name = "noCameraPermissionTitle") @field:Json(name = "noCameraPermissionTitle") var noCameraPermissionTitle: String,
        @Json(name = "noCameraPermissionMessage") @field:Json(name = "noCameraPermissionMessage") var noCameraPermissionMessage: String
)

