/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package dk.nodes.nstack.kotlin.codegen.models

import com.squareup.moshi.Json

/**
 * 
 * @property title 
 * @property message 
 * @property email 
 * @property emailPlaceholder 
 * @property button 
 * @property emailNotFound 
 * @property emailSent 
 * @property invalidEmail 
 * @property emailHasBeenSent 
 * @property instructions 
 * @property backToLogin 
 */
data class ForgotPassword (
        @Json(name = "title") @field:Json(name = "title") var title: String,
        @Json(name = "message") @field:Json(name = "message") var message: String,
        @Json(name = "email") @field:Json(name = "email") var email: String,
        @Json(name = "emailPlaceholder") @field:Json(name = "emailPlaceholder") var emailPlaceholder: String,
        @Json(name = "button") @field:Json(name = "button") var button: String,
        @Json(name = "emailNotFound") @field:Json(name = "emailNotFound") var emailNotFound: String,
        @Json(name = "emailSent") @field:Json(name = "emailSent") var emailSent: String,
        @Json(name = "invalidEmail") @field:Json(name = "invalidEmail") var invalidEmail: String,
        @Json(name = "emailHasBeenSent") @field:Json(name = "emailHasBeenSent") var emailHasBeenSent: String,
        @Json(name = "instructions") @field:Json(name = "instructions") var instructions: String,
        @Json(name = "backToLogin") @field:Json(name = "backToLogin") var backToLogin: String
)

