/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package dk.nodes.nstack.kotlin.codegen.models

import com.squareup.moshi.Json

/**
 * 
 * @property step1Title 
 * @property step1Text 
 * @property step2Title 
 * @property step2Text 
 * @property step3Title 
 * @property step3Text 
 * @property newStep1Title 
 * @property newStep1Text 
 * @property newStep2Title 
 * @property newStep2Text 
 * @property newStep3Title 
 * @property newStep3Text 
 * @property newStep4Title 
 * @property newStep4Text 
 * @property newStep5Title 
 * @property newStep5Text 
 * @property onboardingScreenIdeas 
 * @property onboardingScreenArtists 
 * @property onboardingScreenShops 
 * @property ideas 
 * @property shops 
 * @property artists 
 * @property onboardingScreen1 
 * @property onboardingScreen2 
 * @property onboardingScreen3 
 * @property onboardingScreen4 
 */
data class Introtour (
        @Json(name = "step1Title") @field:Json(name = "step1Title") var step1Title: String,
        @Json(name = "step1Text") @field:Json(name = "step1Text") var step1Text: String,
        @Json(name = "step2Title") @field:Json(name = "step2Title") var step2Title: String,
        @Json(name = "step2Text") @field:Json(name = "step2Text") var step2Text: String,
        @Json(name = "step3Title") @field:Json(name = "step3Title") var step3Title: String,
        @Json(name = "step3Text") @field:Json(name = "step3Text") var step3Text: String,
        @Json(name = "newStep1Title") @field:Json(name = "newStep1Title") var newStep1Title: String,
        @Json(name = "newStep1Text") @field:Json(name = "newStep1Text") var newStep1Text: String,
        @Json(name = "newStep2Title") @field:Json(name = "newStep2Title") var newStep2Title: String,
        @Json(name = "newStep2Text") @field:Json(name = "newStep2Text") var newStep2Text: String,
        @Json(name = "newStep3Title") @field:Json(name = "newStep3Title") var newStep3Title: String,
        @Json(name = "newStep3Text") @field:Json(name = "newStep3Text") var newStep3Text: String,
        @Json(name = "newStep4Title") @field:Json(name = "newStep4Title") var newStep4Title: String,
        @Json(name = "newStep4Text") @field:Json(name = "newStep4Text") var newStep4Text: String,
        @Json(name = "newStep5Title") @field:Json(name = "newStep5Title") var newStep5Title: String,
        @Json(name = "newStep5Text") @field:Json(name = "newStep5Text") var newStep5Text: String,
        @Json(name = "onboardingScreenIdeas") @field:Json(name = "onboardingScreenIdeas") var onboardingScreenIdeas: String,
        @Json(name = "onboardingScreenArtists") @field:Json(name = "onboardingScreenArtists") var onboardingScreenArtists: String,
        @Json(name = "onboardingScreenShops") @field:Json(name = "onboardingScreenShops") var onboardingScreenShops: String,
        @Json(name = "ideas") @field:Json(name = "ideas") var ideas: String,
        @Json(name = "shops") @field:Json(name = "shops") var shops: String,
        @Json(name = "artists") @field:Json(name = "artists") var artists: String,
        @Json(name = "onboardingScreen1") @field:Json(name = "onboardingScreen1") var onboardingScreen1: String,
        @Json(name = "onboardingScreen2") @field:Json(name = "onboardingScreen2") var onboardingScreen2: String,
        @Json(name = "onboardingScreen3") @field:Json(name = "onboardingScreen3") var onboardingScreen3: String,
        @Json(name = "onboardingScreen4") @field:Json(name = "onboardingScreen4") var onboardingScreen4: String
)

