/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package dk.nodes.nstack.kotlin.codegen.models

import com.squareup.moshi.Json

/**
 * 
 * @property acceptLanguage 
 */
data class Meta3 (
        @Json(name = "accept_Language") @field:Json(name = "accept_Language") var acceptLanguage: String
)

