/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package dk.nodes.nstack.kotlin.codegen.models

import com.squareup.moshi.Json

/**
 * 
 * @property Accept-Language 
 */
data class Meta (
        @Json(name = "Accept-Language") @field:Json(name = "Accept-Language") var Accept-Language: String
)

