/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package dk.nodes.nstack.kotlin.codegen.models

import com.squareup.moshi.Json

/**
 * 
 * @property thankYouForYourFeedback 
 * @property thankYouDescription 
 * @property close 
 * @property spreadYourFeedbackAndroid 
 * @property spreadYourFeedbackIOS 
 * @property noThanks 
 * @property reviewApp 
 * @property howWouldYouRateTheTattoodoApp 
 * @property tapTheStars 
 */
data class RatingPrompt (
        @Json(name = "thankYouForYourFeedback") @field:Json(name = "thankYouForYourFeedback") var thankYouForYourFeedback: String,
        @Json(name = "thankYouDescription") @field:Json(name = "thankYouDescription") var thankYouDescription: String,
        @Json(name = "close") @field:Json(name = "close") var close: String,
        @Json(name = "spreadYourFeedbackAndroid") @field:Json(name = "spreadYourFeedbackAndroid") var spreadYourFeedbackAndroid: String,
        @Json(name = "spreadYourFeedbackIOS") @field:Json(name = "spreadYourFeedbackIOS") var spreadYourFeedbackIOS: String,
        @Json(name = "noThanks") @field:Json(name = "noThanks") var noThanks: String,
        @Json(name = "reviewApp") @field:Json(name = "reviewApp") var reviewApp: String,
        @Json(name = "howWouldYouRateTheTattoodoApp") @field:Json(name = "howWouldYouRateTheTattoodoApp") var howWouldYouRateTheTattoodoApp: String,
        @Json(name = "tapTheStars") @field:Json(name = "tapTheStars") var tapTheStars: String
)

