/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package dk.nodes.nstack.kotlin.codegen.models

import com.squareup.moshi.Json

/**
 * 
 * @property inappropriateusers 
 * @property shouldnotbelistedusers 
 * @property inappropriateshops 
 * @property isnotshopshops 
 * @property shouldnotbelistedshops 
 * @property othershops 
 * @property inappropriateposts 
 * @property otherposts 
 * @property otherusers 
 * @property inappropriatecomments 
 * @property falseinformationcomments 
 * @property othercomments 
 * @property falseinformationreviews 
 * @property inappropriatereviews 
 * @property otherreviews 
 * @property yourReason 
 * @property report 
 * @property cancel 
 * @property shopAlreadyReported 
 * @property userAlreadyReported 
 * @property postAlreadyReported 
 * @property reviewAlreadyReported 
 * @property responseAlreadyReported 
 * @property shopReported 
 * @property userReported 
 * @property postReported 
 * @property reviewReported 
 * @property responseReported 
 */
data class Reports (
        @Json(name = "inappropriateusers") @field:Json(name = "inappropriateusers") var inappropriateusers: String,
        @Json(name = "shouldnotbelistedusers") @field:Json(name = "shouldnotbelistedusers") var shouldnotbelistedusers: String,
        @Json(name = "inappropriateshops") @field:Json(name = "inappropriateshops") var inappropriateshops: String,
        @Json(name = "isnotshopshops") @field:Json(name = "isnotshopshops") var isnotshopshops: String,
        @Json(name = "shouldnotbelistedshops") @field:Json(name = "shouldnotbelistedshops") var shouldnotbelistedshops: String,
        @Json(name = "othershops") @field:Json(name = "othershops") var othershops: String,
        @Json(name = "inappropriateposts") @field:Json(name = "inappropriateposts") var inappropriateposts: String,
        @Json(name = "otherposts") @field:Json(name = "otherposts") var otherposts: String,
        @Json(name = "otherusers") @field:Json(name = "otherusers") var otherusers: String,
        @Json(name = "inappropriatecomments") @field:Json(name = "inappropriatecomments") var inappropriatecomments: String,
        @Json(name = "falseinformationcomments") @field:Json(name = "falseinformationcomments") var falseinformationcomments: String,
        @Json(name = "othercomments") @field:Json(name = "othercomments") var othercomments: String,
        @Json(name = "falseinformationreviews") @field:Json(name = "falseinformationreviews") var falseinformationreviews: String,
        @Json(name = "inappropriatereviews") @field:Json(name = "inappropriatereviews") var inappropriatereviews: String,
        @Json(name = "otherreviews") @field:Json(name = "otherreviews") var otherreviews: String,
        @Json(name = "yourReason") @field:Json(name = "yourReason") var yourReason: String,
        @Json(name = "report") @field:Json(name = "report") var report: String,
        @Json(name = "cancel") @field:Json(name = "cancel") var cancel: String,
        @Json(name = "shopAlreadyReported") @field:Json(name = "shopAlreadyReported") var shopAlreadyReported: String,
        @Json(name = "userAlreadyReported") @field:Json(name = "userAlreadyReported") var userAlreadyReported: String,
        @Json(name = "postAlreadyReported") @field:Json(name = "postAlreadyReported") var postAlreadyReported: String,
        @Json(name = "reviewAlreadyReported") @field:Json(name = "reviewAlreadyReported") var reviewAlreadyReported: String,
        @Json(name = "responseAlreadyReported") @field:Json(name = "responseAlreadyReported") var responseAlreadyReported: String,
        @Json(name = "shopReported") @field:Json(name = "shopReported") var shopReported: String,
        @Json(name = "userReported") @field:Json(name = "userReported") var userReported: String,
        @Json(name = "postReported") @field:Json(name = "postReported") var postReported: String,
        @Json(name = "reviewReported") @field:Json(name = "reviewReported") var reviewReported: String,
        @Json(name = "responseReported") @field:Json(name = "responseReported") var responseReported: String
)

