/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package dk.nodes.nstack.kotlin.codegen.models

import com.squareup.moshi.Json

/**
 * 
 * @property signUpWithEmail 
 * @property email 
 * @property password 
 * @property login 
 * @property signUp 
 * @property alreadyHaveAnAccount 
 * @property pleaseEnterValidEmail 
 * @property emailAlreadyTaken 
 * @property passwordTooShort 
 */
data class SignUp (
        @Json(name = "signUpWithEmail") @field:Json(name = "signUpWithEmail") var signUpWithEmail: String,
        @Json(name = "email") @field:Json(name = "email") var email: String,
        @Json(name = "password") @field:Json(name = "password") var password: String,
        @Json(name = "login") @field:Json(name = "login") var login: String,
        @Json(name = "signUp") @field:Json(name = "signUp") var signUp: String,
        @Json(name = "alreadyHaveAnAccount") @field:Json(name = "alreadyHaveAnAccount") var alreadyHaveAnAccount: String,
        @Json(name = "pleaseEnterValidEmail") @field:Json(name = "pleaseEnterValidEmail") var pleaseEnterValidEmail: String,
        @Json(name = "emailAlreadyTaken") @field:Json(name = "emailAlreadyTaken") var emailAlreadyTaken: String,
        @Json(name = "passwordTooShort") @field:Json(name = "passwordTooShort") var passwordTooShort: String
)

