/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package dk.nodes.nstack.kotlin.codegen.models

import com.squareup.moshi.Json

/**
 * 
 * @property titleFacebook 
 * @property followSelected 
 * @property selectAll 
 * @property deselectAll 
 * @property friendsReadyToConnect 
 * @property friendReadyToConnect 
 * @property titlePopular 
 * @property suggestions 
 * @property noUsersFound 
 * @property fbLoginRequiredMessage 
 * @property fbLoginRequiredTitle 
 * @property fbLoginButton 
 * @property fbLoginFailed 
 * @property fbLoginAccountInUse 
 * @property followers 
 * @property noFacebookFriendsTitle 
 * @property noFacebookFriendsMessage 
 * @property weSuggest 
 * @property continueButton 
 */
data class SuggestUsers (
        @Json(name = "titleFacebook") @field:Json(name = "titleFacebook") var titleFacebook: String,
        @Json(name = "followSelected") @field:Json(name = "followSelected") var followSelected: String,
        @Json(name = "selectAll") @field:Json(name = "selectAll") var selectAll: String,
        @Json(name = "deselectAll") @field:Json(name = "deselectAll") var deselectAll: String,
        @Json(name = "friendsReadyToConnect") @field:Json(name = "friendsReadyToConnect") var friendsReadyToConnect: String,
        @Json(name = "friendReadyToConnect") @field:Json(name = "friendReadyToConnect") var friendReadyToConnect: String,
        @Json(name = "titlePopular") @field:Json(name = "titlePopular") var titlePopular: String,
        @Json(name = "suggestions") @field:Json(name = "suggestions") var suggestions: String,
        @Json(name = "noUsersFound") @field:Json(name = "noUsersFound") var noUsersFound: String,
        @Json(name = "fbLoginRequiredMessage") @field:Json(name = "fbLoginRequiredMessage") var fbLoginRequiredMessage: String,
        @Json(name = "fbLoginRequiredTitle") @field:Json(name = "fbLoginRequiredTitle") var fbLoginRequiredTitle: String,
        @Json(name = "fbLoginButton") @field:Json(name = "fbLoginButton") var fbLoginButton: String,
        @Json(name = "fbLoginFailed") @field:Json(name = "fbLoginFailed") var fbLoginFailed: String,
        @Json(name = "fbLoginAccountInUse") @field:Json(name = "fbLoginAccountInUse") var fbLoginAccountInUse: String,
        @Json(name = "followers") @field:Json(name = "followers") var followers: String,
        @Json(name = "noFacebookFriendsTitle") @field:Json(name = "noFacebookFriendsTitle") var noFacebookFriendsTitle: String,
        @Json(name = "noFacebookFriendsMessage") @field:Json(name = "noFacebookFriendsMessage") var noFacebookFriendsMessage: String,
        @Json(name = "weSuggest") @field:Json(name = "weSuggest") var weSuggest: String,
        @Json(name = "continueButton") @field:Json(name = "continueButton") var continueButton: String
)

