/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package dk.nodes.nstack.kotlin.codegen.models

import com.squareup.moshi.Json

/**
 * 
 * @property activeModalActivate 
 * @property activeModalDeactivate 
 * @property activeTooltipActivate 
 * @property activeTooltipDeactivate 
 * @property addTitle 
 * @property connection 
 * @property defaultModalText 
 * @property defaultSavedSuccess 
 * @property defaultTooltip 
 * @property exportTooltip 
 * @property importTooltip 
 * @property keysTooltip 
 * @property setDefault 
 * @property test 
 * @property testModalTextActivate 
 * @property testModalTextDeactivate 
 * @property testSaveSuccessActivate 
 * @property testSaveSuccessDeactivate 
 * @property testTooltipActivate 
 * @property testTooltipDeactivate 
 * @property theConnection 
 * @property title 
 */
data class TranslatePlatformLanguages (
        @Json(name = "activeModalActivate") @field:Json(name = "activeModalActivate") var activeModalActivate: String,
        @Json(name = "activeModalDeactivate") @field:Json(name = "activeModalDeactivate") var activeModalDeactivate: String,
        @Json(name = "activeTooltipActivate") @field:Json(name = "activeTooltipActivate") var activeTooltipActivate: String,
        @Json(name = "activeTooltipDeactivate") @field:Json(name = "activeTooltipDeactivate") var activeTooltipDeactivate: String,
        @Json(name = "addTitle") @field:Json(name = "addTitle") var addTitle: String,
        @Json(name = "connection") @field:Json(name = "connection") var connection: String,
        @Json(name = "defaultModalText") @field:Json(name = "defaultModalText") var defaultModalText: String,
        @Json(name = "defaultSavedSuccess") @field:Json(name = "defaultSavedSuccess") var defaultSavedSuccess: String,
        @Json(name = "defaultTooltip") @field:Json(name = "defaultTooltip") var defaultTooltip: String,
        @Json(name = "exportTooltip") @field:Json(name = "exportTooltip") var exportTooltip: String,
        @Json(name = "importTooltip") @field:Json(name = "importTooltip") var importTooltip: String,
        @Json(name = "keysTooltip") @field:Json(name = "keysTooltip") var keysTooltip: String,
        @Json(name = "setDefault") @field:Json(name = "setDefault") var setDefault: String,
        @Json(name = "test") @field:Json(name = "test") var test: String,
        @Json(name = "testModalTextActivate") @field:Json(name = "testModalTextActivate") var testModalTextActivate: String,
        @Json(name = "testModalTextDeactivate") @field:Json(name = "testModalTextDeactivate") var testModalTextDeactivate: String,
        @Json(name = "testSaveSuccessActivate") @field:Json(name = "testSaveSuccessActivate") var testSaveSuccessActivate: String,
        @Json(name = "testSaveSuccessDeactivate") @field:Json(name = "testSaveSuccessDeactivate") var testSaveSuccessDeactivate: String,
        @Json(name = "testTooltipActivate") @field:Json(name = "testTooltipActivate") var testTooltipActivate: String,
        @Json(name = "testTooltipDeactivate") @field:Json(name = "testTooltipDeactivate") var testTooltipDeactivate: String,
        @Json(name = "theConnection") @field:Json(name = "theConnection") var theConnection: String,
        @Json(name = "title") @field:Json(name = "title") var title: String
)

