/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package dk.nodes.nstack.kotlin.codegen.models

import com.squareup.moshi.Json

/**
 * 
 * @property skipButton 
 * @property facebookButton 
 * @property twitterButton 
 * @property emailButton 
 * @property twitterErrorAlert 
 * @property facebookErrorAlert 
 * @property cantFindFacebookAccount 
 * @property cantFindTwitterAccount 
 * @property googleButton 
 * @property googleErrorAlert 
 * @property cantFindGoogleAccount 
 * @property bySigningUp 
 * @property headerText 
 * @property termsAndPrivacy 
 * @property termsOfConditions 
 * @property and 
 * @property privacy 
 * @property betaCodeErrorAlert 
 * @property connecting 
 * @property newSkipButton 
 * @property worldsLargestTattooCommunity 
 * @property google 
 * @property facebook 
 * @property twitter 
 * @property loginOrSignUpWithEmail 
 * @property terms 
 * @property youAgreeBySigningUp 
 * @property privacyPolicy 
 * @property continueWith 
 * @property continueWithEmail 
 */
data class Welcome (
        @Json(name = "skipButton") @field:Json(name = "skipButton") var skipButton: String,
        @Json(name = "facebookButton") @field:Json(name = "facebookButton") var facebookButton: String,
        @Json(name = "twitterButton") @field:Json(name = "twitterButton") var twitterButton: String,
        @Json(name = "emailButton") @field:Json(name = "emailButton") var emailButton: String,
        @Json(name = "twitterErrorAlert") @field:Json(name = "twitterErrorAlert") var twitterErrorAlert: String,
        @Json(name = "facebookErrorAlert") @field:Json(name = "facebookErrorAlert") var facebookErrorAlert: String,
        @Json(name = "cantFindFacebookAccount") @field:Json(name = "cantFindFacebookAccount") var cantFindFacebookAccount: String,
        @Json(name = "cantFindTwitterAccount") @field:Json(name = "cantFindTwitterAccount") var cantFindTwitterAccount: String,
        @Json(name = "googleButton") @field:Json(name = "googleButton") var googleButton: String,
        @Json(name = "googleErrorAlert") @field:Json(name = "googleErrorAlert") var googleErrorAlert: String,
        @Json(name = "cantFindGoogleAccount") @field:Json(name = "cantFindGoogleAccount") var cantFindGoogleAccount: String,
        @Json(name = "bySigningUp") @field:Json(name = "bySigningUp") var bySigningUp: String,
        @Json(name = "headerText") @field:Json(name = "headerText") var headerText: String,
        @Json(name = "termsAndPrivacy") @field:Json(name = "termsAndPrivacy") var termsAndPrivacy: String,
        @Json(name = "termsOfConditions") @field:Json(name = "termsOfConditions") var termsOfConditions: String,
        @Json(name = "and") @field:Json(name = "and") var and: String,
        @Json(name = "privacy") @field:Json(name = "privacy") var privacy: String,
        @Json(name = "betaCodeErrorAlert") @field:Json(name = "betaCodeErrorAlert") var betaCodeErrorAlert: String,
        @Json(name = "connecting") @field:Json(name = "connecting") var connecting: String,
        @Json(name = "newSkipButton") @field:Json(name = "newSkipButton") var newSkipButton: String,
        @Json(name = "worldsLargestTattooCommunity") @field:Json(name = "worldsLargestTattooCommunity") var worldsLargestTattooCommunity: String,
        @Json(name = "google") @field:Json(name = "google") var google: String,
        @Json(name = "facebook") @field:Json(name = "facebook") var facebook: String,
        @Json(name = "twitter") @field:Json(name = "twitter") var twitter: String,
        @Json(name = "loginOrSignUpWithEmail") @field:Json(name = "loginOrSignUpWithEmail") var loginOrSignUpWithEmail: String,
        @Json(name = "terms") @field:Json(name = "terms") var terms: String,
        @Json(name = "youAgreeBySigningUp") @field:Json(name = "youAgreeBySigningUp") var youAgreeBySigningUp: String,
        @Json(name = "privacyPolicy") @field:Json(name = "privacyPolicy") var privacyPolicy: String,
        @Json(name = "continueWith") @field:Json(name = "continueWith") var continueWith: String,
        @Json(name = "continueWithEmail") @field:Json(name = "continueWithEmail") var continueWithEmail: String
)

