//
// AnswerRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AnswerRequest: Codable {

    public var guid: String
    public var answer: String

    public init(guid: String, answer: String) {
        self.guid = guid
        self.answer = answer
    }

}
