//
// AppOpenData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AppOpenData: Codable {

    public var count: Int
    public var update: Update
    public var localize: [Localize]
    public var rateReminder: RateReminder
    public var platform: String
    public var createdAt: String
    public var lastUpdated: String

    public init(count: Int, update: Update, localize: [Localize], rateReminder: RateReminder, platform: String, createdAt: String, lastUpdated: String) {
        self.count = count
        self.update = update
        self.localize = localize
        self.rateReminder = rateReminder
        self.platform = platform
        self.createdAt = createdAt
        self.lastUpdated = lastUpdated
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case count
        case update
        case localize
        case rateReminder = "rate_reminder"
        case platform
        case createdAt = "created_at"
        case lastUpdated = "last_updated"
    }

}
