//
// Artist.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Artist: Codable {

    public var tattooArtistAt: String
    public var skills: String
    public var guest: String
    public var allWorkplaces: String
    public var add: String
    public var edit: String
    public var addWorkplace: String
    public var done: String
    public var areYouGuest: String
    public var startDate: String
    public var endDate: String
    public var chooseMaxSkills: String
    public var alreadyPickedTitle: String
    public var alreadyPickedDescription: String
    public var ok: String
    public var okay: String
    public var searchShops: String
    public var showYourExperience: String
    public var cantFindShop: String
    public var createShop: String
    public var noResultsFor: String
    public var theShopDoesNotExist: String
    public var cancel: String
    public var use: String
    public var name: String
    public var deleteThisPromptTitle: String
    public var deleteThisPromptDescription: String
    public var present: String
    public var createNew: String
    public var editWorkplace: String
    public var pleaseSelectStartDate: String
    public var pleaseSelectEndDateAfterStartDate: String
    public var workplaces: String
    public var now: String
    public var sharePortfolio: String
    public var noWorkplaces: String
    public var noWorkplacesSubtitle: String
    public var delete: String
    public var searchArtists: String
    public var work: String
    public var preferredStyles: String
    public var worksAt: String
    public var about: String
    public var whereDoYouWork: String
    public var previousWorkplaces: String
    public var guestArtist: String
    public var tabWork: String
    public var tabBoards: String
    public var tabAbout: String
    public var addBio: String
    public var noBio: String
    public var styles: String
    public var noStyles: String
    public var noStylesSubtitle: String
    public var addStyles: String
    public var tabMyCollection: String

    public init(tattooArtistAt: String, skills: String, guest: String, allWorkplaces: String, add: String, edit: String, addWorkplace: String, done: String, areYouGuest: String, startDate: String, endDate: String, chooseMaxSkills: String, alreadyPickedTitle: String, alreadyPickedDescription: String, ok: String, okay: String, searchShops: String, showYourExperience: String, cantFindShop: String, createShop: String, noResultsFor: String, theShopDoesNotExist: String, cancel: String, use: String, name: String, deleteThisPromptTitle: String, deleteThisPromptDescription: String, present: String, createNew: String, editWorkplace: String, pleaseSelectStartDate: String, pleaseSelectEndDateAfterStartDate: String, workplaces: String, now: String, sharePortfolio: String, noWorkplaces: String, noWorkplacesSubtitle: String, delete: String, searchArtists: String, work: String, preferredStyles: String, worksAt: String, about: String, whereDoYouWork: String, previousWorkplaces: String, guestArtist: String, tabWork: String, tabBoards: String, tabAbout: String, addBio: String, noBio: String, styles: String, noStyles: String, noStylesSubtitle: String, addStyles: String, tabMyCollection: String) {
        self.tattooArtistAt = tattooArtistAt
        self.skills = skills
        self.guest = guest
        self.allWorkplaces = allWorkplaces
        self.add = add
        self.edit = edit
        self.addWorkplace = addWorkplace
        self.done = done
        self.areYouGuest = areYouGuest
        self.startDate = startDate
        self.endDate = endDate
        self.chooseMaxSkills = chooseMaxSkills
        self.alreadyPickedTitle = alreadyPickedTitle
        self.alreadyPickedDescription = alreadyPickedDescription
        self.ok = ok
        self.okay = okay
        self.searchShops = searchShops
        self.showYourExperience = showYourExperience
        self.cantFindShop = cantFindShop
        self.createShop = createShop
        self.noResultsFor = noResultsFor
        self.theShopDoesNotExist = theShopDoesNotExist
        self.cancel = cancel
        self.use = use
        self.name = name
        self.deleteThisPromptTitle = deleteThisPromptTitle
        self.deleteThisPromptDescription = deleteThisPromptDescription
        self.present = present
        self.createNew = createNew
        self.editWorkplace = editWorkplace
        self.pleaseSelectStartDate = pleaseSelectStartDate
        self.pleaseSelectEndDateAfterStartDate = pleaseSelectEndDateAfterStartDate
        self.workplaces = workplaces
        self.now = now
        self.sharePortfolio = sharePortfolio
        self.noWorkplaces = noWorkplaces
        self.noWorkplacesSubtitle = noWorkplacesSubtitle
        self.delete = delete
        self.searchArtists = searchArtists
        self.work = work
        self.preferredStyles = preferredStyles
        self.worksAt = worksAt
        self.about = about
        self.whereDoYouWork = whereDoYouWork
        self.previousWorkplaces = previousWorkplaces
        self.guestArtist = guestArtist
        self.tabWork = tabWork
        self.tabBoards = tabBoards
        self.tabAbout = tabAbout
        self.addBio = addBio
        self.noBio = noBio
        self.styles = styles
        self.noStyles = noStyles
        self.noStylesSubtitle = noStylesSubtitle
        self.addStyles = addStyles
        self.tabMyCollection = tabMyCollection
    }

}
