//
// BodyPart.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct BodyPart: Codable {

    public var title: String
    public var _none: String
    public var arms: String
    public var legs: String
    public var torso: String
    public var head: String
    public var _left: String
    public var _right: String

    public init(title: String, _none: String, arms: String, legs: String, torso: String, head: String, _left: String, _right: String) {
        self.title = title
        self._none = _none
        self.arms = arms
        self.legs = legs
        self.torso = torso
        self.head = head
        self._left = _left
        self._right = _right
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case title
        case _none = "none"
        case arms
        case legs
        case torso
        case head
        case _left = "left"
        case _right = "right"
    }

}
