//
// Booking.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Booking: Codable {

    public var bookingError: String
    public var title: String
    public var subtitle: String
    public var phoneNumberTitle: String
    public var phoneNumberHint: String
    public var preferredArtistTitle: String
    public var preferredArtistHint: String
    public var describeTattooTitle: String
    public var describeTattooHint: String
    public var requestNowButton: String
    public var contactInformationButton: String
    public var bookingConfirmationTitle: String
    public var bookingConfirmationSubtitle: String
    public var bookingConfirmationButtonLabel: String

    public init(bookingError: String, title: String, subtitle: String, phoneNumberTitle: String, phoneNumberHint: String, preferredArtistTitle: String, preferredArtistHint: String, describeTattooTitle: String, describeTattooHint: String, requestNowButton: String, contactInformationButton: String, bookingConfirmationTitle: String, bookingConfirmationSubtitle: String, bookingConfirmationButtonLabel: String) {
        self.bookingError = bookingError
        self.title = title
        self.subtitle = subtitle
        self.phoneNumberTitle = phoneNumberTitle
        self.phoneNumberHint = phoneNumberHint
        self.preferredArtistTitle = preferredArtistTitle
        self.preferredArtistHint = preferredArtistHint
        self.describeTattooTitle = describeTattooTitle
        self.describeTattooHint = describeTattooHint
        self.requestNowButton = requestNowButton
        self.contactInformationButton = contactInformationButton
        self.bookingConfirmationTitle = bookingConfirmationTitle
        self.bookingConfirmationSubtitle = bookingConfirmationSubtitle
        self.bookingConfirmationButtonLabel = bookingConfirmationButtonLabel
    }

}
