//
// Communication.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Communication: Codable {

    public var notifications: String
    public var deny: String
    public var accept: String
    public var wantsToAddYou: String
    public var noNotifications: String
    public var noNotificationsSubtitle: String
    public var commentPost: String
    public var likePost: String
    public var mentionInComment: String
    public var followingYou: String
    public var pinPost: String
    public var mentionInPost: String
    public var mentionInArticle: String
    public var shopReviewResponse: String
    public var acceptingInvitation: String

    public init(notifications: String, deny: String, accept: String, wantsToAddYou: String, noNotifications: String, noNotificationsSubtitle: String, commentPost: String, likePost: String, mentionInComment: String, followingYou: String, pinPost: String, mentionInPost: String, mentionInArticle: String, shopReviewResponse: String, acceptingInvitation: String) {
        self.notifications = notifications
        self.deny = deny
        self.accept = accept
        self.wantsToAddYou = wantsToAddYou
        self.noNotifications = noNotifications
        self.noNotificationsSubtitle = noNotificationsSubtitle
        self.commentPost = commentPost
        self.likePost = likePost
        self.mentionInComment = mentionInComment
        self.followingYou = followingYou
        self.pinPost = pinPost
        self.mentionInPost = mentionInPost
        self.mentionInArticle = mentionInArticle
        self.shopReviewResponse = shopReviewResponse
        self.acceptingInvitation = acceptingInvitation
    }

}
