//
// CreateUser2.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CreateUser2: Codable {

    public var title: String
    public var password: String
    public var passwordPlaceholder: String
    public var repeatPassword: String
    public var repeatPasswordPlaceholder: String
    public var continueButton: String
    public var passwordsDontMatch: String
    public var passwordValidationFailed: String
    public var _required: String
    public var tooShort: String
    public var passwordsMatch: String

    public init(title: String, password: String, passwordPlaceholder: String, repeatPassword: String, repeatPasswordPlaceholder: String, continueButton: String, passwordsDontMatch: String, passwordValidationFailed: String, _required: String, tooShort: String, passwordsMatch: String) {
        self.title = title
        self.password = password
        self.passwordPlaceholder = passwordPlaceholder
        self.repeatPassword = repeatPassword
        self.repeatPasswordPlaceholder = repeatPasswordPlaceholder
        self.continueButton = continueButton
        self.passwordsDontMatch = passwordsDontMatch
        self.passwordValidationFailed = passwordValidationFailed
        self._required = _required
        self.tooShort = tooShort
        self.passwordsMatch = passwordsMatch
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case title
        case password
        case passwordPlaceholder
        case repeatPassword
        case repeatPasswordPlaceholder
        case continueButton
        case passwordsDontMatch
        case passwordValidationFailed
        case _required = "required"
        case tooShort
        case passwordsMatch
    }

}
