//
// CreateNewPostDescription.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CreateNewPostDescription: Codable {

    public var chooseBodyPart: String
    public var title: String
    public var isThisYourBody: String
    public var shareButton: String
    public var posting: String
    public var descriptionPlaceholder: String
    public var editPostTitle: String

    public init(chooseBodyPart: String, title: String, isThisYourBody: String, shareButton: String, posting: String, descriptionPlaceholder: String, editPostTitle: String) {
        self.chooseBodyPart = chooseBodyPart
        self.title = title
        self.isThisYourBody = isThisYourBody
        self.shareButton = shareButton
        self.posting = posting
        self.descriptionPlaceholder = descriptionPlaceholder
        self.editPostTitle = editPostTitle
    }

}
