//
// CreateUser3.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CreateUser3: Codable {

    public var type: String
    public var tattooShop: String
    public var artist: String
    public var standard: String

    public init(type: String, tattooShop: String, artist: String, standard: String) {
        self.type = type
        self.tattooShop = tattooShop
        self.artist = artist
        self.standard = standard
    }

}
