//
// EndOfFeed.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct EndOfFeed: Codable {

    public var discoverMore: String
    public var tattoos: String

    public init(discoverMore: String, tattoos: String) {
        self.discoverMore = discoverMore
        self.tattoos = tattoos
    }

}
