//
// Errors.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Errors: Codable {

    public var invalidOrMissingFields: String
    public var emailAlreadyInUse: String
    public var title: String
    public var facebookTokenVerificationFailed: String
    public var twitterTokenVerificationFailed: String
    public var unknownError: String
    public var incorrectPassword: String
    public var newPasswordTooShort: String
    public var loginNeeded: String
    public var loginButton: String
    public var loginNeededTitle: String
    public var connectionErrorTitle: String
    public var connectionError: String
    public var tryAgain: String
    public var cancel: String
    public var giveCameraAccessText: String
    public var giveLibraryAccessText: String
    public var giveAccessButton: String
    public var noCameraAccessText: String
    public var openSettingsButton: String
    public var noLibraryAccessText: String
    public var canNotSendEmailMessage: String
    public var invalidToken: String
    public var couldntFindUser: String
    public var tokenExpired: String
    public var invalidAcceptHeader: String
    public var couldntFindEntity: String
    public var twitterLoginErrorTitle: String
    public var couldntFindImage: String
    public var invalidTokenTitle: String
    public var noCameraAccessTextAndroid: String
    public var noLibraryAccessTextAndroid: String
    public var cameraConnectionError: String
    public var loginCanceledTitle: String
    public var loginCanceledMessage: String
    public var loginFailedTitle: String
    public var loginFailedMessage: String
    public var shopsCannotPinPosts: String
    public var invalidImage: String
    public var invalidShopName: String
    public var fieldRequired: String
    public var passwordErrorCharacter: String
    public var passwordErrorTooShort: String
    public var passwordErrorIncorrect: String
    public var invalidImageTitle: String
    public var failedToLoadContent: String
    public var checkIfYouHaveAnInternetConnection: String
    public var pullToRefresh: String
    public var noCameraPermissionTitle: String
    public var noCameraPermissionMessage: String

    public init(invalidOrMissingFields: String, emailAlreadyInUse: String, title: String, facebookTokenVerificationFailed: String, twitterTokenVerificationFailed: String, unknownError: String, incorrectPassword: String, newPasswordTooShort: String, loginNeeded: String, loginButton: String, loginNeededTitle: String, connectionErrorTitle: String, connectionError: String, tryAgain: String, cancel: String, giveCameraAccessText: String, giveLibraryAccessText: String, giveAccessButton: String, noCameraAccessText: String, openSettingsButton: String, noLibraryAccessText: String, canNotSendEmailMessage: String, invalidToken: String, couldntFindUser: String, tokenExpired: String, invalidAcceptHeader: String, couldntFindEntity: String, twitterLoginErrorTitle: String, couldntFindImage: String, invalidTokenTitle: String, noCameraAccessTextAndroid: String, noLibraryAccessTextAndroid: String, cameraConnectionError: String, loginCanceledTitle: String, loginCanceledMessage: String, loginFailedTitle: String, loginFailedMessage: String, shopsCannotPinPosts: String, invalidImage: String, invalidShopName: String, fieldRequired: String, passwordErrorCharacter: String, passwordErrorTooShort: String, passwordErrorIncorrect: String, invalidImageTitle: String, failedToLoadContent: String, checkIfYouHaveAnInternetConnection: String, pullToRefresh: String, noCameraPermissionTitle: String, noCameraPermissionMessage: String) {
        self.invalidOrMissingFields = invalidOrMissingFields
        self.emailAlreadyInUse = emailAlreadyInUse
        self.title = title
        self.facebookTokenVerificationFailed = facebookTokenVerificationFailed
        self.twitterTokenVerificationFailed = twitterTokenVerificationFailed
        self.unknownError = unknownError
        self.incorrectPassword = incorrectPassword
        self.newPasswordTooShort = newPasswordTooShort
        self.loginNeeded = loginNeeded
        self.loginButton = loginButton
        self.loginNeededTitle = loginNeededTitle
        self.connectionErrorTitle = connectionErrorTitle
        self.connectionError = connectionError
        self.tryAgain = tryAgain
        self.cancel = cancel
        self.giveCameraAccessText = giveCameraAccessText
        self.giveLibraryAccessText = giveLibraryAccessText
        self.giveAccessButton = giveAccessButton
        self.noCameraAccessText = noCameraAccessText
        self.openSettingsButton = openSettingsButton
        self.noLibraryAccessText = noLibraryAccessText
        self.canNotSendEmailMessage = canNotSendEmailMessage
        self.invalidToken = invalidToken
        self.couldntFindUser = couldntFindUser
        self.tokenExpired = tokenExpired
        self.invalidAcceptHeader = invalidAcceptHeader
        self.couldntFindEntity = couldntFindEntity
        self.twitterLoginErrorTitle = twitterLoginErrorTitle
        self.couldntFindImage = couldntFindImage
        self.invalidTokenTitle = invalidTokenTitle
        self.noCameraAccessTextAndroid = noCameraAccessTextAndroid
        self.noLibraryAccessTextAndroid = noLibraryAccessTextAndroid
        self.cameraConnectionError = cameraConnectionError
        self.loginCanceledTitle = loginCanceledTitle
        self.loginCanceledMessage = loginCanceledMessage
        self.loginFailedTitle = loginFailedTitle
        self.loginFailedMessage = loginFailedMessage
        self.shopsCannotPinPosts = shopsCannotPinPosts
        self.invalidImage = invalidImage
        self.invalidShopName = invalidShopName
        self.fieldRequired = fieldRequired
        self.passwordErrorCharacter = passwordErrorCharacter
        self.passwordErrorTooShort = passwordErrorTooShort
        self.passwordErrorIncorrect = passwordErrorIncorrect
        self.invalidImageTitle = invalidImageTitle
        self.failedToLoadContent = failedToLoadContent
        self.checkIfYouHaveAnInternetConnection = checkIfYouHaveAnInternetConnection
        self.pullToRefresh = pullToRefresh
        self.noCameraPermissionTitle = noCameraPermissionTitle
        self.noCameraPermissionMessage = noCameraPermissionMessage
    }

}
