//
// InlineObject6.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject6: Codable {

    public var name: String
    public var tags: String
    public var goneAt: String
    public var file: String
    public var privacy: String

    public init(name: String, tags: String, goneAt: String, file: String, privacy: String) {
        self.name = name
        self.tags = tags
        self.goneAt = goneAt
        self.file = file
        self.privacy = privacy
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case name
        case tags
        case goneAt = "gone_at"
        case file
        case privacy
    }

}
