//
// InlineObject14.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject14: Codable {

    public var guid: Int
    public var platform: String
    public var answer: String

    public init(guid: Int, platform: String, answer: String) {
        self.guid = guid
        self.platform = platform
        self.answer = answer
    }

}
