//
// Language1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Language1: Codable {

    public var title: String
    public var english: String
    public var defaultLanguage: String
    public var enGB: String
    public var daDK: String
    public var frFR: String
    public var ruRU: String
    public var ptBR: String
    public var zhCN: String

    public init(title: String, english: String, defaultLanguage: String, enGB: String, daDK: String, frFR: String, ruRU: String, ptBR: String, zhCN: String) {
        self.title = title
        self.english = english
        self.defaultLanguage = defaultLanguage
        self.enGB = enGB
        self.daDK = daDK
        self.frFR = frFR
        self.ruRU = ruRU
        self.ptBR = ptBR
        self.zhCN = zhCN
    }

}
