//
// Languagebestfit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Languagebestfit: Codable {

    public var data: ModelData
    public var meta: Meta

    public init(data: ModelData, meta: Meta) {
        self.data = data
        self.meta = meta
    }

}
