//
// NewerVersion.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct NewerVersion: Codable {

    public var state: String
    public var lastId: Int
    public var version: String
    public var link: String
    public var translate: Translate

    public init(state: String, lastId: Int, version: String, link: String, translate: Translate) {
        self.state = state
        self.lastId = lastId
        self.version = version
        self.link = link
        self.translate = translate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case state
        case lastId = "last_id"
        case version
        case link
        case translate
    }

}
