//
// People.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct People: Codable {

    public var searchPeople: String

    public init(searchPeople: String) {
        self.searchPeople = searchPeople
    }

}
