//
// Pin.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Pin: Codable {

    public var pinPostSuccess: String
    public var pinPostError: String
    public var create: String
    public var image: String
    public var images: String
    public var editBoardTitle: String
    public var createNewBoard: String
    public var privateBoard: String
    public var boardTitlePlaceholder: String
    public var cancel: String
    public var save: String
    public var boardDeleteError: String
    public var edit: String
    public var delete: String
    public var deleteBoard: String
    public var deleteBoardMessage: String
    public var pin: String
    public var pins: String
    public var selectBoard: String
    public var addToBoard: String
    public var uploads: String
    public var pinners: String
    public var selectBoardEmpty: String
    public var selectBoardEmptySubtitle: String
    public var createBoard: String
    public var boards: String
    public var createNew: String
    public var saved: String

    public init(pinPostSuccess: String, pinPostError: String, create: String, image: String, images: String, editBoardTitle: String, createNewBoard: String, privateBoard: String, boardTitlePlaceholder: String, cancel: String, save: String, boardDeleteError: String, edit: String, delete: String, deleteBoard: String, deleteBoardMessage: String, pin: String, pins: String, selectBoard: String, addToBoard: String, uploads: String, pinners: String, selectBoardEmpty: String, selectBoardEmptySubtitle: String, createBoard: String, boards: String, createNew: String, saved: String) {
        self.pinPostSuccess = pinPostSuccess
        self.pinPostError = pinPostError
        self.create = create
        self.image = image
        self.images = images
        self.editBoardTitle = editBoardTitle
        self.createNewBoard = createNewBoard
        self.privateBoard = privateBoard
        self.boardTitlePlaceholder = boardTitlePlaceholder
        self.cancel = cancel
        self.save = save
        self.boardDeleteError = boardDeleteError
        self.edit = edit
        self.delete = delete
        self.deleteBoard = deleteBoard
        self.deleteBoardMessage = deleteBoardMessage
        self.pin = pin
        self.pins = pins
        self.selectBoard = selectBoard
        self.addToBoard = addToBoard
        self.uploads = uploads
        self.pinners = pinners
        self.selectBoardEmpty = selectBoardEmpty
        self.selectBoardEmptySubtitle = selectBoardEmptySubtitle
        self.createBoard = createBoard
        self.boards = boards
        self.createNew = createNew
        self.saved = saved
    }

}
