//
// PushLogsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PushLogsRequest: Codable {

    public var provider: String
    public var key: String
    public var type: String
    public var succeeded: Bool
    public var request: Any
    public var response: Any
    public var userId: Int

    public init(provider: String, key: String, type: String, succeeded: Bool, request: Any, response: Any, userId: Int) {
        self.provider = provider
        self.key = key
        self.type = type
        self.succeeded = succeeded
        self.request = request
        self.response = response
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case provider
        case key
        case type
        case succeeded
        case request
        case response
        case userId = "user_id"
    }

}
