//
// Reports.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Reports: Codable {

    public var inappropriateusers: String
    public var shouldnotbelistedusers: String
    public var inappropriateshops: String
    public var isnotshopshops: String
    public var shouldnotbelistedshops: String
    public var othershops: String
    public var inappropriateposts: String
    public var otherposts: String
    public var otherusers: String
    public var inappropriatecomments: String
    public var falseinformationcomments: String
    public var othercomments: String
    public var falseinformationreviews: String
    public var inappropriatereviews: String
    public var otherreviews: String
    public var yourReason: String
    public var report: String
    public var cancel: String
    public var shopAlreadyReported: String
    public var userAlreadyReported: String
    public var postAlreadyReported: String
    public var reviewAlreadyReported: String
    public var responseAlreadyReported: String
    public var shopReported: String
    public var userReported: String
    public var postReported: String
    public var reviewReported: String
    public var responseReported: String

    public init(inappropriateusers: String, shouldnotbelistedusers: String, inappropriateshops: String, isnotshopshops: String, shouldnotbelistedshops: String, othershops: String, inappropriateposts: String, otherposts: String, otherusers: String, inappropriatecomments: String, falseinformationcomments: String, othercomments: String, falseinformationreviews: String, inappropriatereviews: String, otherreviews: String, yourReason: String, report: String, cancel: String, shopAlreadyReported: String, userAlreadyReported: String, postAlreadyReported: String, reviewAlreadyReported: String, responseAlreadyReported: String, shopReported: String, userReported: String, postReported: String, reviewReported: String, responseReported: String) {
        self.inappropriateusers = inappropriateusers
        self.shouldnotbelistedusers = shouldnotbelistedusers
        self.inappropriateshops = inappropriateshops
        self.isnotshopshops = isnotshopshops
        self.shouldnotbelistedshops = shouldnotbelistedshops
        self.othershops = othershops
        self.inappropriateposts = inappropriateposts
        self.otherposts = otherposts
        self.otherusers = otherusers
        self.inappropriatecomments = inappropriatecomments
        self.falseinformationcomments = falseinformationcomments
        self.othercomments = othercomments
        self.falseinformationreviews = falseinformationreviews
        self.inappropriatereviews = inappropriatereviews
        self.otherreviews = otherreviews
        self.yourReason = yourReason
        self.report = report
        self.cancel = cancel
        self.shopAlreadyReported = shopAlreadyReported
        self.userAlreadyReported = userAlreadyReported
        self.postAlreadyReported = postAlreadyReported
        self.reviewAlreadyReported = reviewAlreadyReported
        self.responseAlreadyReported = responseAlreadyReported
        self.shopReported = shopReported
        self.userReported = userReported
        self.postReported = postReported
        self.reviewReported = reviewReported
        self.responseReported = responseReported
    }

}
