//
// Scropper.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Scropper: Codable {

    public var xaxis: Double
    public var yaxis: Double
    public var faceBb: [FaceBb]

    public init(xaxis: Double, yaxis: Double, faceBb: [FaceBb]) {
        self.xaxis = xaxis
        self.yaxis = yaxis
        self.faceBb = faceBb
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case xaxis
        case yaxis
        case faceBb = "face_bb"
    }

}
