//
// Settings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Settings: Codable {

    public var editProfile: String
    public var title: String
    public var findFacebookFriends: String
    public var pushNotifications: String
    public var language: String
    public var appTour: String
    public var giveFeedback: String
    public var terms: String
    public var version: String
    public var feedbackMailRecipients: String
    public var feedbackMailSubject: String
    public var feedbackMailBody: String
    public var termsHTML: String
    public var privacyHTML: String
    public var privacy: String
    public var logoutConfirmationTitle: String
    public var findFacebookFriendsDescription: String
    public var appTourDescription: String
    public var giveFeedbackDescription: String
    public var termsDescription: String
    public var connectWithTwitter: String
    public var connectWithGooglePlus: String
    public var connectWithTwitterDescription: String
    public var connectWithGooglePlusDescription: String
    public var connectWithTwitterSuccess: String
    public var connectWithGooglePlusSuccess: String
    public var addSocialMediaError: String
    public var connectWithFacebook: String
    public var connectWithFacebookDescription: String
    public var connectWithFacebookSuccess: String
    public var connectWithGooglePlusConnected: String
    public var connectWithTwitterSuccessConnected: String
    public var twitterLoginAccountInUse: String
    public var googlePlusAlreadyRegistered: String
    public var options: String
    public var general: String
    public var upgradeToArtist: String
    public var addTattooShop: String
    public var findFriends: String
    public var account: String
    public var app: String
    public var rateApp: String
    public var switchTo: String
    public var email: String
    public var changePassword: String
    public var connectWithGoogle: String
    public var termsAndConditions: String
    public var about: String
    public var done: String
    public var cancel: String
    public var newPassword: String
    public var repeatPassword: String
    public var inviteFromFacebook: String
    public var ofYourFriends: String
    public var keepUp: String
    public var followAll: String
    public var follow: String
    public var following: String
    public var logOut: String
    public var sureYouWantToLogOut: String
    public var upgradeTitle: String
    public var upgradeText: String
    public var upgrade: String
    public var socialConnections: String
    public var personal: String
    public var connectedWithFacebook: String
    public var connectedWithGoogle: String
    public var connectedWithTwitter: String
    public var aboutHTML: String
    public var backToOptions: String
    public var successAllSet: String
    public var yourShopIsNowAPartOfTattoodo: String
    public var goToShop: String
    public var faqHTML: String
    public var faq: String
    public var thirdPartyLicenses: String
    public var switchProfile: String
    public var pushNotificationsDescription: String

    public init(editProfile: String, title: String, findFacebookFriends: String, pushNotifications: String, language: String, appTour: String, giveFeedback: String, terms: String, version: String, feedbackMailRecipients: String, feedbackMailSubject: String, feedbackMailBody: String, termsHTML: String, privacyHTML: String, privacy: String, logoutConfirmationTitle: String, findFacebookFriendsDescription: String, appTourDescription: String, giveFeedbackDescription: String, termsDescription: String, connectWithTwitter: String, connectWithGooglePlus: String, connectWithTwitterDescription: String, connectWithGooglePlusDescription: String, connectWithTwitterSuccess: String, connectWithGooglePlusSuccess: String, addSocialMediaError: String, connectWithFacebook: String, connectWithFacebookDescription: String, connectWithFacebookSuccess: String, connectWithGooglePlusConnected: String, connectWithTwitterSuccessConnected: String, twitterLoginAccountInUse: String, googlePlusAlreadyRegistered: String, options: String, general: String, upgradeToArtist: String, addTattooShop: String, findFriends: String, account: String, app: String, rateApp: String, switchTo: String, email: String, changePassword: String, connectWithGoogle: String, termsAndConditions: String, about: String, done: String, cancel: String, newPassword: String, repeatPassword: String, inviteFromFacebook: String, ofYourFriends: String, keepUp: String, followAll: String, follow: String, following: String, logOut: String, sureYouWantToLogOut: String, upgradeTitle: String, upgradeText: String, upgrade: String, socialConnections: String, personal: String, connectedWithFacebook: String, connectedWithGoogle: String, connectedWithTwitter: String, aboutHTML: String, backToOptions: String, successAllSet: String, yourShopIsNowAPartOfTattoodo: String, goToShop: String, faqHTML: String, faq: String, thirdPartyLicenses: String, switchProfile: String, pushNotificationsDescription: String) {
        self.editProfile = editProfile
        self.title = title
        self.findFacebookFriends = findFacebookFriends
        self.pushNotifications = pushNotifications
        self.language = language
        self.appTour = appTour
        self.giveFeedback = giveFeedback
        self.terms = terms
        self.version = version
        self.feedbackMailRecipients = feedbackMailRecipients
        self.feedbackMailSubject = feedbackMailSubject
        self.feedbackMailBody = feedbackMailBody
        self.termsHTML = termsHTML
        self.privacyHTML = privacyHTML
        self.privacy = privacy
        self.logoutConfirmationTitle = logoutConfirmationTitle
        self.findFacebookFriendsDescription = findFacebookFriendsDescription
        self.appTourDescription = appTourDescription
        self.giveFeedbackDescription = giveFeedbackDescription
        self.termsDescription = termsDescription
        self.connectWithTwitter = connectWithTwitter
        self.connectWithGooglePlus = connectWithGooglePlus
        self.connectWithTwitterDescription = connectWithTwitterDescription
        self.connectWithGooglePlusDescription = connectWithGooglePlusDescription
        self.connectWithTwitterSuccess = connectWithTwitterSuccess
        self.connectWithGooglePlusSuccess = connectWithGooglePlusSuccess
        self.addSocialMediaError = addSocialMediaError
        self.connectWithFacebook = connectWithFacebook
        self.connectWithFacebookDescription = connectWithFacebookDescription
        self.connectWithFacebookSuccess = connectWithFacebookSuccess
        self.connectWithGooglePlusConnected = connectWithGooglePlusConnected
        self.connectWithTwitterSuccessConnected = connectWithTwitterSuccessConnected
        self.twitterLoginAccountInUse = twitterLoginAccountInUse
        self.googlePlusAlreadyRegistered = googlePlusAlreadyRegistered
        self.options = options
        self.general = general
        self.upgradeToArtist = upgradeToArtist
        self.addTattooShop = addTattooShop
        self.findFriends = findFriends
        self.account = account
        self.app = app
        self.rateApp = rateApp
        self.switchTo = switchTo
        self.email = email
        self.changePassword = changePassword
        self.connectWithGoogle = connectWithGoogle
        self.termsAndConditions = termsAndConditions
        self.about = about
        self.done = done
        self.cancel = cancel
        self.newPassword = newPassword
        self.repeatPassword = repeatPassword
        self.inviteFromFacebook = inviteFromFacebook
        self.ofYourFriends = ofYourFriends
        self.keepUp = keepUp
        self.followAll = followAll
        self.follow = follow
        self.following = following
        self.logOut = logOut
        self.sureYouWantToLogOut = sureYouWantToLogOut
        self.upgradeTitle = upgradeTitle
        self.upgradeText = upgradeText
        self.upgrade = upgrade
        self.socialConnections = socialConnections
        self.personal = personal
        self.connectedWithFacebook = connectedWithFacebook
        self.connectedWithGoogle = connectedWithGoogle
        self.connectedWithTwitter = connectedWithTwitter
        self.aboutHTML = aboutHTML
        self.backToOptions = backToOptions
        self.successAllSet = successAllSet
        self.yourShopIsNowAPartOfTattoodo = yourShopIsNowAPartOfTattoodo
        self.goToShop = goToShop
        self.faqHTML = faqHTML
        self.faq = faq
        self.thirdPartyLicenses = thirdPartyLicenses
        self.switchProfile = switchProfile
        self.pushNotificationsDescription = pushNotificationsDescription
    }

}
