//
// Tattoos.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Tattoos: Codable {

    public var searchTattoos: String
    public var tattoosOfTheDay: String

    public init(searchTattoos: String, tattoosOfTheDay: String) {
        self.searchTattoos = searchTattoos
        self.tattoosOfTheDay = tattoosOfTheDay
    }

}
