//
// TranslateLanguages.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TranslateLanguages: Codable {

    public var deleteLanguageModalText: String
    public var title: String

    public init(deleteLanguageModalText: String, title: String) {
        self.deleteLanguageModalText = deleteLanguageModalText
        self.title = title
    }

}
