//
// TranslateMain.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TranslateMain: Codable {

    public var addSectionBtn: String
    public var addSectionTitle: String
    public var cacheFlushedSuccess: String
    public var deleteKeyModalText: String
    public var deleteSectionEmptyKeysModelText: String
    public var deleteSectionModalText: String
    public var flushCache: String
    public var updateValueModalTitle: String

    public init(addSectionBtn: String, addSectionTitle: String, cacheFlushedSuccess: String, deleteKeyModalText: String, deleteSectionEmptyKeysModelText: String, deleteSectionModalText: String, flushCache: String, updateValueModalTitle: String) {
        self.addSectionBtn = addSectionBtn
        self.addSectionTitle = addSectionTitle
        self.cacheFlushedSuccess = cacheFlushedSuccess
        self.deleteKeyModalText = deleteKeyModalText
        self.deleteSectionEmptyKeysModelText = deleteSectionEmptyKeysModelText
        self.deleteSectionModalText = deleteSectionModalText
        self.flushCache = flushCache
        self.updateValueModalTitle = updateValueModalTitle
    }

}
