//
// TranslateImport.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TranslateImport: Codable {

    public var submitBtn: String
    public var title: String

    public init(submitBtn: String, title: String) {
        self.submitBtn = submitBtn
        self.title = title
    }

}
