//
// TranslatePlatforms.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TranslatePlatforms: Codable {

    public var addNewModalHeader: String
    public var deletePlatformModalText: String
    public var inProductionModalTextActivate: String
    public var inProductionModalTextDeactivate: String
    public var inProductionTooltipActivate: String
    public var inProductionTooltipDeactivate: String
    public var isInDevelopmentFlash: String
    public var isInProductionFlash: String
    public var keysTooltip: String
    public var platformLanguageTooltip: String
    public var title: String

    public init(addNewModalHeader: String, deletePlatformModalText: String, inProductionModalTextActivate: String, inProductionModalTextDeactivate: String, inProductionTooltipActivate: String, inProductionTooltipDeactivate: String, isInDevelopmentFlash: String, isInProductionFlash: String, keysTooltip: String, platformLanguageTooltip: String, title: String) {
        self.addNewModalHeader = addNewModalHeader
        self.deletePlatformModalText = deletePlatformModalText
        self.inProductionModalTextActivate = inProductionModalTextActivate
        self.inProductionModalTextDeactivate = inProductionModalTextDeactivate
        self.inProductionTooltipActivate = inProductionTooltipActivate
        self.inProductionTooltipDeactivate = inProductionTooltipDeactivate
        self.isInDevelopmentFlash = isInDevelopmentFlash
        self.isInProductionFlash = isInProductionFlash
        self.keysTooltip = keysTooltip
        self.platformLanguageTooltip = platformLanguageTooltip
        self.title = title
    }

}
