//
// TranslateDefault.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TranslateDefault: Codable {

    public var autoRedirectToFirstPlatform: String
    public var direction: String
    public var inProduction: String
    public var key: String
    public var keys: String
    public var language: String
    public var languages: String
    public var locale: String
    public var lrm: String
    public var platforms: String
    public var rlm: String
    public var section: String
    public var sections: String
    public var theKey: String
    public var theLanguage: String
    public var thePlatform: String
    public var theSection: String
    public var theTranslation: String
    public var translated: String
    public var translation: String
    public var value: String

    public init(autoRedirectToFirstPlatform: String, direction: String, inProduction: String, key: String, keys: String, language: String, languages: String, locale: String, lrm: String, platforms: String, rlm: String, section: String, sections: String, theKey: String, theLanguage: String, thePlatform: String, theSection: String, theTranslation: String, translated: String, translation: String, value: String) {
        self.autoRedirectToFirstPlatform = autoRedirectToFirstPlatform
        self.direction = direction
        self.inProduction = inProduction
        self.key = key
        self.keys = keys
        self.language = language
        self.languages = languages
        self.locale = locale
        self.lrm = lrm
        self.platforms = platforms
        self.rlm = rlm
        self.section = section
        self.sections = sections
        self.theKey = theKey
        self.theLanguage = theLanguage
        self.thePlatform = thePlatform
        self.theSection = theSection
        self.theTranslation = theTranslation
        self.translated = translated
        self.translation = translation
        self.value = value
    }

}
