//
// User1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct User1: Codable {

    public var firstName: String
    public var lastName: String

    public init(firstName: String, lastName: String) {
        self.firstName = firstName
        self.lastName = lastName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case firstName = "first_name"
        case lastName = "last_name"
    }

}
