//
// User.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct User: Codable {

    public var titleProfile: String
    public var posts: String
    public var followers: String
    public var following: String
    public var noPhotos: String
    public var doesNotExist: String
    public var follow: String
    public var isFollowing: String
    public var onlyMyTattoos: String
    public var thisUserDoesntExist: String
    public var myTattoos: String
    public var someonesActivity: String
    public var report: String
    public var reportMessage: String
    public var reportSuccess: String
    public var reportTitle: String
    public var userAlreadyReportedTitle: String
    public var userNotFoundMessage: String
    public var tattoosOnMyBody: String
    public var unfollowUser: String
    public var unfollowUserMessage: String
    public var unfollowUnfollowButton: String
    public var unfollowCancelButton: String
    public var uploadedByMe: String
    public var myCollection: String
    public var bio: String
    public var tabMyCollection: String
    public var tabBoards: String
    public var tabUploads: String
    public var noBoards: String
    public var emptyBoards: String
    public var emptyBoardsSubtitle: String
    public var noBoardsSubtitle: String
    public var noMyCollection: String
    public var noMyCollectionSubtitle: String
    public var addTattoos: String
    public var emptyMyCollection: String
    public var emptyMyCollectionSubtitle: String
    public var noUploads: String
    public var noUploadsSubtitle: String
    public var emptyUploads: String
    public var emptyUploadsSubtitle: String
    public var uploadIdeas: String

    public init(titleProfile: String, posts: String, followers: String, following: String, noPhotos: String, doesNotExist: String, follow: String, isFollowing: String, onlyMyTattoos: String, thisUserDoesntExist: String, myTattoos: String, someonesActivity: String, report: String, reportMessage: String, reportSuccess: String, reportTitle: String, userAlreadyReportedTitle: String, userNotFoundMessage: String, tattoosOnMyBody: String, unfollowUser: String, unfollowUserMessage: String, unfollowUnfollowButton: String, unfollowCancelButton: String, uploadedByMe: String, myCollection: String, bio: String, tabMyCollection: String, tabBoards: String, tabUploads: String, noBoards: String, emptyBoards: String, emptyBoardsSubtitle: String, noBoardsSubtitle: String, noMyCollection: String, noMyCollectionSubtitle: String, addTattoos: String, emptyMyCollection: String, emptyMyCollectionSubtitle: String, noUploads: String, noUploadsSubtitle: String, emptyUploads: String, emptyUploadsSubtitle: String, uploadIdeas: String) {
        self.titleProfile = titleProfile
        self.posts = posts
        self.followers = followers
        self.following = following
        self.noPhotos = noPhotos
        self.doesNotExist = doesNotExist
        self.follow = follow
        self.isFollowing = isFollowing
        self.onlyMyTattoos = onlyMyTattoos
        self.thisUserDoesntExist = thisUserDoesntExist
        self.myTattoos = myTattoos
        self.someonesActivity = someonesActivity
        self.report = report
        self.reportMessage = reportMessage
        self.reportSuccess = reportSuccess
        self.reportTitle = reportTitle
        self.userAlreadyReportedTitle = userAlreadyReportedTitle
        self.userNotFoundMessage = userNotFoundMessage
        self.tattoosOnMyBody = tattoosOnMyBody
        self.unfollowUser = unfollowUser
        self.unfollowUserMessage = unfollowUserMessage
        self.unfollowUnfollowButton = unfollowUnfollowButton
        self.unfollowCancelButton = unfollowCancelButton
        self.uploadedByMe = uploadedByMe
        self.myCollection = myCollection
        self.bio = bio
        self.tabMyCollection = tabMyCollection
        self.tabBoards = tabBoards
        self.tabUploads = tabUploads
        self.noBoards = noBoards
        self.emptyBoards = emptyBoards
        self.emptyBoardsSubtitle = emptyBoardsSubtitle
        self.noBoardsSubtitle = noBoardsSubtitle
        self.noMyCollection = noMyCollection
        self.noMyCollectionSubtitle = noMyCollectionSubtitle
        self.addTattoos = addTattoos
        self.emptyMyCollection = emptyMyCollection
        self.emptyMyCollectionSubtitle = emptyMyCollectionSubtitle
        self.noUploads = noUploads
        self.noUploadsSubtitle = noUploadsSubtitle
        self.emptyUploads = emptyUploads
        self.emptyUploadsSubtitle = emptyUploadsSubtitle
        self.uploadIdeas = uploadIdeas
    }

}
