//
// MessagesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



open class MessagesAPI {
    /**
     Markasseen
     
     - parameter xApplicationId: (header)  
     - parameter xRestApiKey: (header)  
     - parameter guid: (form)  
     - parameter messageId: (form)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func markasseen(xApplicationId: String, xRestApiKey: String, guid: Int, messageId: Int, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: MarkAsSeenResponse?,_ error: Error?) -> Void)) {
        markasseenWithRequestBuilder(xApplicationId: xApplicationId, xRestApiKey: xRestApiKey, guid: guid, messageId: messageId).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Markasseen
     - POST /api/v2/notify/messages/views
     - Register a view update  #### Request details Method: `POST`  URL: `/api/v2/notify/updates/views`  #### Headers  `X-Application-Id` (string) **required** _Application ID from [NStack](https://nstack.io)_  `X-Rest-Api-Key` (string) **required** _Rest API key from [NStack](https://nstack.io)_  #### Parameters `guid` (int) **required** _[?]_  `message_id` **required** _[?]_  #### Response codes `200` OK  `412` Precondition failed
     - parameter xApplicationId: (header)  
     - parameter xRestApiKey: (header)  
     - parameter guid: (form)  
     - parameter messageId: (form)  
     - returns: RequestBuilder<MarkAsSeenResponse> 
     */
    open class func markasseenWithRequestBuilder(xApplicationId: String, xRestApiKey: String, guid: Int, messageId: Int) -> RequestBuilder<MarkAsSeenResponse> {
        let path = "/api/v2/notify/messages/views"
        let URLString = OpenAPIClientAPI.basePath + path
        let formParams: [String:Any?] = [
            "guid": guid.encodeToJSON(),
            "message_id": messageId.encodeToJSON()
        ]

        let nonNullParameters = APIHelper.rejectNil(formParams)
        let parameters = APIHelper.convertBoolToString(nonNullParameters)
        
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
            "X-Application-Id": xApplicationId.encodeToJSON(),
            "X-Rest-Api-Key": xRestApiKey.encodeToJSON()
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<MarkAsSeenResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**
     Messages
     
     - parameter platform: (query)  
     - parameter xApplicationId: (header)  
     - parameter xRestApiKey: (header)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func messages(platform: String, xApplicationId: String, xRestApiKey: String, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: Messages?,_ error: Error?) -> Void)) {
        messagesWithRequestBuilder(platform: platform, xApplicationId: xApplicationId, xRestApiKey: xRestApiKey).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Messages
     - GET /api/v2/notify/messages
     - Get message  #### Request details Method:    `GET`  URL:    `/api/v1/notify/messages`  #### Headers  `X-Application-Id` (string) **required** _Application ID from [NStack](https://nstack.io)_  `X-Rest-Api-Key` (string) **required** _Rest API key from [NStack](https://nstack.io)_  #### Query parameters `platform` (string) **required** _[\"ios\", \"android\", \"windows\", \"web\"]_   #### Response codes `200` OK  `412` Precondition failed
     - responseHeaders: [Server(String), Transfer-Encoding(String), Connection(String), Cache-Control(String), Date(String)]
     - parameter platform: (query)  
     - parameter xApplicationId: (header)  
     - parameter xRestApiKey: (header)  
     - returns: RequestBuilder<Messages> 
     */
    open class func messagesWithRequestBuilder(platform: String, xApplicationId: String, xRestApiKey: String) -> RequestBuilder<Messages> {
        let path = "/api/v2/notify/messages"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "platform": platform.encodeToJSON()
        ])
        let nillableHeaders: [String: Any?] = [
            "X-Application-Id": xApplicationId.encodeToJSON(),
            "X-Rest-Api-Key": xRestApiKey.encodeToJSON()
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Messages>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**
     Messages1
     
     - parameter platform: (query)  
     - parameter xApplicationId: (header)  
     - parameter xRestApiKey: (header)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func messages1(platform: String, xApplicationId: String, xRestApiKey: String, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: Messages?,_ error: Error?) -> Void)) {
        messages1WithRequestBuilder(platform: platform, xApplicationId: xApplicationId, xRestApiKey: xRestApiKey).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Messages1
     - GET /api/v1/notify/messages
     - Get message  #### Request details Method:    `GET`  URL:    `/api/v1/notify/messages`  #### Headers  `X-Application-Id` (string) **required** _Application ID from [NStack](https://nstack.io)_  `X-Rest-Api-Key` (string) **required** _Rest API key from [NStack](https://nstack.io)_  #### Query parameters `platform` (string) **required** _[\"ios\", \"android\", \"windows\", \"web\"]_   #### Response codes `200` OK  `412` Precondition failed
     - responseHeaders: [Server(String), Transfer-Encoding(String), Connection(String), Cache-Control(String), Date(String)]
     - parameter platform: (query)  
     - parameter xApplicationId: (header)  
     - parameter xRestApiKey: (header)  
     - returns: RequestBuilder<Messages> 
     */
    open class func messages1WithRequestBuilder(platform: String, xApplicationId: String, xRestApiKey: String) -> RequestBuilder<Messages> {
        let path = "/api/v1/notify/messages"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "platform": platform.encodeToJSON()
        ])
        let nillableHeaders: [String: Any?] = [
            "X-Application-Id": xApplicationId.encodeToJSON(),
            "X-Rest-Api-Key": xRestApiKey.encodeToJSON()
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Messages>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**
     Viewmessage
     
     - parameter xApplicationId: (header)  
     - parameter xRestApiKey: (header)  
     - parameter guid: (form)  
     - parameter messageId: (form)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func viewmessage(xApplicationId: String, xRestApiKey: String, guid: Int, messageId: Int, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        viewmessageWithRequestBuilder(xApplicationId: xApplicationId, xRestApiKey: xRestApiKey, guid: guid, messageId: messageId).execute(apiResponseQueue) { result -> Void in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Viewmessage
     - POST /api/v1/notify/messages/views
     - Register a view update  #### Request details Method: `POST`  URL: `/api/v1/notify/updates/views`  #### Headers  `X-Application-Id` (string) **required** _Application ID from [NStack](https://nstack.io)_  `X-Rest-Api-Key` (string) **required** _Rest API key from [NStack](https://nstack.io)_  #### Parameters `guid` (int) **required** _[?]_  `message_id` **required** _[?]_  #### Response codes `200` OK  `412` Precondition failed
     - parameter xApplicationId: (header)  
     - parameter xRestApiKey: (header)  
     - parameter guid: (form)  
     - parameter messageId: (form)  
     - returns: RequestBuilder<Void> 
     */
    open class func viewmessageWithRequestBuilder(xApplicationId: String, xRestApiKey: String, guid: Int, messageId: Int) -> RequestBuilder<Void> {
        let path = "/api/v1/notify/messages/views"
        let URLString = OpenAPIClientAPI.basePath + path
        let formParams: [String:Any?] = [
            "guid": guid.encodeToJSON(),
            "message_id": messageId.encodeToJSON()
        ]

        let nonNullParameters = APIHelper.rejectNil(formParams)
        let parameters = APIHelper.convertBoolToString(nonNullParameters)
        
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
            "X-Application-Id": xApplicationId.encodeToJSON(),
            "X-Rest-Api-Key": xRestApiKey.encodeToJSON()
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = OpenAPIClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

}
