/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 2.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import com.squareup.moshi.Json
/**
 * 
 * @param key 
 * @param user 
 * @param answer 
 * @param points 
 * @param tag 
 */

data class InlineObject11 (
    @Json(name = "key")
    val key: kotlin.String,
    @Json(name = "user")
    val user: kotlin.String,
    @Json(name = "answer")
    val answer: kotlin.Array<kotlin.Int>,
    @Json(name = "points")
    val points: kotlin.Int,
    @Json(name = "tag")
    val tag: kotlin.String
) 



