/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import com.squareup.moshi.Json
/**
 * 
 * @param notifications 
 * @param deny 
 * @param accept 
 * @param wantsToAddYou 
 * @param noNotifications 
 * @param noNotificationsSubtitle 
 * @param commentPost 
 * @param likePost 
 * @param mentionInComment 
 * @param followingYou 
 * @param pinPost 
 * @param mentionInPost 
 * @param mentionInArticle 
 * @param shopReviewResponse 
 * @param acceptingInvitation 
 */

data class Communication (
    @Json(name = "notifications")
    val notifications: kotlin.String,
    @Json(name = "deny")
    val deny: kotlin.String,
    @Json(name = "accept")
    val accept: kotlin.String,
    @Json(name = "wantsToAddYou")
    val wantsToAddYou: kotlin.String,
    @Json(name = "noNotifications")
    val noNotifications: kotlin.String,
    @Json(name = "noNotificationsSubtitle")
    val noNotificationsSubtitle: kotlin.String,
    @Json(name = "commentPost")
    val commentPost: kotlin.String,
    @Json(name = "likePost")
    val likePost: kotlin.String,
    @Json(name = "mentionInComment")
    val mentionInComment: kotlin.String,
    @Json(name = "followingYou")
    val followingYou: kotlin.String,
    @Json(name = "pinPost")
    val pinPost: kotlin.String,
    @Json(name = "mentionInPost")
    val mentionInPost: kotlin.String,
    @Json(name = "mentionInArticle")
    val mentionInArticle: kotlin.String,
    @Json(name = "shopReviewResponse")
    val shopReviewResponse: kotlin.String,
    @Json(name = "acceptingInvitation")
    val acceptingInvitation: kotlin.String
) 



