/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import com.squareup.moshi.Json
/**
 * 
 * @param empty 
 * @param placeholder 
 * @param title 
 * @param post 
 * @param success 
 * @param add 
 * @param reply 
 * @param suggestedProfiles 
 * @param skip 
 * @param emptySubtitle 
 */

data class Comments (
    @Json(name = "empty")
    val empty: kotlin.String,
    @Json(name = "placeholder")
    val placeholder: kotlin.String,
    @Json(name = "title")
    val title: kotlin.String,
    @Json(name = "post")
    val post: kotlin.String,
    @Json(name = "success")
    val success: kotlin.String,
    @Json(name = "add")
    val add: kotlin.String,
    @Json(name = "reply")
    val reply: kotlin.String,
    @Json(name = "suggestedProfiles")
    val suggestedProfiles: kotlin.String,
    @Json(name = "skip")
    val skip: kotlin.String,
    @Json(name = "emptySubtitle")
    val emptySubtitle: kotlin.String
) 



