/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import com.squareup.moshi.Json
/**
 * 
 * @param ok 
 * @param required 
 * @param cancel 
 * @param done 
 * @param male 
 * @param female 
 * @param errorRandomErrorAlertText 
 * @param ago 
 * @param now 
 * @param open 
 * @param openLinkTitle 
 * @param openLinkMessage 
 * @param justNow 
 * @param aMinuteAgo 
 * @param anHourAgo 
 * @param hoursAgo 
 * @param yesterday 
 * @param week 
 * @param weeks 
 * @param month 
 * @param months 
 * @param minutesAgo 
 * @param youGotANewFollower 
 * @param dAgo 
 * @param sAgo 
 * @param retry 
 * @param back 
 * @param pressBackAgain 
 * @param picture 
 * @param fullSecond 
 * @param fullSeconds 
 * @param fullMinute 
 * @param fullMinutes 
 * @param fullHour 
 * @param fullHours 
 * @param fullDay 
 * @param fullDays 
 * @param fullWeek 
 * @param fullWeeks 
 * @param byLowercase 
 * @param monday 
 * @param tuesday 
 * @param wednesday 
 * @param thursday 
 * @param friday 
 * @param saturday 
 * @param sunday 
 * @param iCurrentlyWorkHere 
 * @param distanceAway 
 * @param km 
 * @param hey 
 * @param readMore 
 * @param edit 
 * @param save 
 * @param settings 
 * @param later 
 * @param next 
 * @param previous 
 * @param skip 
 * @param zhCN 
 * @param ptBR 
 * @param yes 
 * @param no 
 */

data class Default (
    @Json(name = "ok")
    val ok: kotlin.String,
    @Json(name = "required")
    val required: kotlin.String,
    @Json(name = "cancel")
    val cancel: kotlin.String,
    @Json(name = "done")
    val done: kotlin.String,
    @Json(name = "male")
    val male: kotlin.String,
    @Json(name = "female")
    val female: kotlin.String,
    @Json(name = "errorRandomErrorAlertText")
    val errorRandomErrorAlertText: kotlin.String,
    @Json(name = "ago")
    val ago: kotlin.String,
    @Json(name = "now")
    val now: kotlin.String,
    @Json(name = "open")
    val open: kotlin.String,
    @Json(name = "openLinkTitle")
    val openLinkTitle: kotlin.String,
    @Json(name = "openLinkMessage")
    val openLinkMessage: kotlin.String,
    @Json(name = "justNow")
    val justNow: kotlin.String,
    @Json(name = "aMinuteAgo")
    val aMinuteAgo: kotlin.String,
    @Json(name = "anHourAgo")
    val anHourAgo: kotlin.String,
    @Json(name = "hoursAgo")
    val hoursAgo: kotlin.String,
    @Json(name = "yesterday")
    val yesterday: kotlin.String,
    @Json(name = "week")
    val week: kotlin.String,
    @Json(name = "weeks")
    val weeks: kotlin.String,
    @Json(name = "month")
    val month: kotlin.String,
    @Json(name = "months")
    val months: kotlin.String,
    @Json(name = "minutesAgo")
    val minutesAgo: kotlin.String,
    @Json(name = "youGotANewFollower")
    val youGotANewFollower: kotlin.String,
    @Json(name = "dAgo")
    val dAgo: kotlin.String,
    @Json(name = "sAgo")
    val sAgo: kotlin.String,
    @Json(name = "retry")
    val retry: kotlin.String,
    @Json(name = "back")
    val back: kotlin.String,
    @Json(name = "pressBackAgain")
    val pressBackAgain: kotlin.String,
    @Json(name = "picture")
    val picture: kotlin.String,
    @Json(name = "fullSecond")
    val fullSecond: kotlin.String,
    @Json(name = "fullSeconds")
    val fullSeconds: kotlin.String,
    @Json(name = "fullMinute")
    val fullMinute: kotlin.String,
    @Json(name = "fullMinutes")
    val fullMinutes: kotlin.String,
    @Json(name = "fullHour")
    val fullHour: kotlin.String,
    @Json(name = "fullHours")
    val fullHours: kotlin.String,
    @Json(name = "fullDay")
    val fullDay: kotlin.String,
    @Json(name = "fullDays")
    val fullDays: kotlin.String,
    @Json(name = "fullWeek")
    val fullWeek: kotlin.String,
    @Json(name = "fullWeeks")
    val fullWeeks: kotlin.String,
    @Json(name = "byLowercase")
    val byLowercase: kotlin.String,
    @Json(name = "monday")
    val monday: kotlin.String,
    @Json(name = "tuesday")
    val tuesday: kotlin.String,
    @Json(name = "wednesday")
    val wednesday: kotlin.String,
    @Json(name = "thursday")
    val thursday: kotlin.String,
    @Json(name = "friday")
    val friday: kotlin.String,
    @Json(name = "saturday")
    val saturday: kotlin.String,
    @Json(name = "sunday")
    val sunday: kotlin.String,
    @Json(name = "iCurrentlyWorkHere")
    val iCurrentlyWorkHere: kotlin.String,
    @Json(name = "distanceAway")
    val distanceAway: kotlin.String,
    @Json(name = "km")
    val km: kotlin.String,
    @Json(name = "hey")
    val hey: kotlin.String,
    @Json(name = "readMore")
    val readMore: kotlin.String,
    @Json(name = "edit")
    val edit: kotlin.String,
    @Json(name = "save")
    val save: kotlin.String,
    @Json(name = "settings")
    val settings: kotlin.String,
    @Json(name = "later")
    val later: kotlin.String,
    @Json(name = "next")
    val next: kotlin.String,
    @Json(name = "previous")
    val previous: kotlin.String,
    @Json(name = "skip")
    val skip: kotlin.String,
    @Json(name = "zhCN")
    val zhCN: kotlin.String,
    @Json(name = "ptBR")
    val ptBR: kotlin.String,
    @Json(name = "yes")
    val yes: kotlin.String? = null,
    @Json(name = "no")
    val no: kotlin.String? = null
) 



