/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import com.squareup.moshi.Json
/**
 * 
 * @param filters 
 * @param reset 
 * @param title 
 * @param imageErrorMessage 
 */

data class EditImage (
    @Json(name = "filters")
    val filters: kotlin.String,
    @Json(name = "reset")
    val reset: kotlin.String,
    @Json(name = "title")
    val title: kotlin.String,
    @Json(name = "imageErrorMessage")
    val imageErrorMessage: kotlin.String
) 



