/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import com.squareup.moshi.Json
/**
 * 
 * @param couldNotFindModelWithId 
 * @param failedToDelete 
 * @param failedToSave 
 * @param random 
 */

data class Errors1 (
    @Json(name = "couldNotFindModelWithId")
    val couldNotFindModelWithId: kotlin.String,
    @Json(name = "failedToDelete")
    val failedToDelete: kotlin.String,
    @Json(name = "failedToSave")
    val failedToSave: kotlin.String,
    @Json(name = "random")
    val random: kotlin.String
) 



