/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import com.squareup.moshi.Json
/**
 * 
 * @param natural 
 * @param dagger 
 * @param koi 
 * @param mandala 
 * @param rose 
 * @param hannya 
 */

data class Filters (
    @Json(name = "natural")
    val natural: kotlin.String,
    @Json(name = "dagger")
    val dagger: kotlin.String,
    @Json(name = "koi")
    val koi: kotlin.String,
    @Json(name = "mandala")
    val mandala: kotlin.String,
    @Json(name = "rose")
    val rose: kotlin.String,
    @Json(name = "hannya")
    val hannya: kotlin.String
) 



