/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import com.squareup.moshi.Json
/**
 * 
 * @param k0int 
 * @param key1string 
 * @param key2float 
 * @param key3wysiwygsim 
 * @param key4asset 
 * @param key5boolean 
 * @param key6wysiwygadvanced 
 */

data class InlineObject4 (
    @Json(name = "k0int")
    val k0int: kotlin.Int,
    @Json(name = "key1string")
    val key1string: kotlin.String,
    @Json(name = "key2float")
    val key2float: kotlin.Double,
    @Json(name = "key3wysiwygsim")
    val key3wysiwygsim: kotlin.String,
    @Json(name = "key4asset")
    val key4asset: kotlin.String,
    @Json(name = "key5boolean")
    val key5boolean: kotlin.Boolean,
    @Json(name = "key6wysiwygadvanced")
    val key6wysiwygadvanced: kotlin.String
) 



