/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import com.squareup.moshi.Json
/**
 * 
 * @param os 
 * @param device 
 * @param appVersion 
 * @param name 
 * @param email 
 * @param message 
 * @param image 
 */

data class InlineObject18 (
    @Json(name = "os")
    val os: kotlin.String,
    @Json(name = "device")
    val device: kotlin.String,
    @Json(name = "app_version")
    val appVersion: kotlin.String,
    @Json(name = "name")
    val name: kotlin.String,
    @Json(name = "email")
    val email: kotlin.String,
    @Json(name = "message")
    val message: kotlin.String,
    @Json(name = "image")
    val image: kotlin.String
) 



