/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import com.squareup.moshi.Json
/**
 * 
 * @param termVersionId 
 * @param guid 
 * @param identifier 
 * @param locale 
 */

data class InlineObject9 (
    @Json(name = "term_version_id")
    val termVersionId: kotlin.Int,
    @Json(name = "guid")
    val guid: kotlin.String,
    @Json(name = "identifier")
    val identifier: kotlin.String,
    @Json(name = "locale")
    val locale: kotlin.String
) 



