/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model

import dk.nodes.nstack.kotlin.codegen.model.Language

import com.squareup.moshi.Json
/**
 * 
 * @param id 
 * @param url 
 * @param lastUpdatedAt 
 * @param shouldUpdate 
 * @param language 
 */

data class Localize (
    @Json(name = "id")
    val id: kotlin.Int,
    @Json(name = "url")
    val url: kotlin.String,
    @Json(name = "last_updated_at")
    val lastUpdatedAt: kotlin.String,
    @Json(name = "should_update")
    val shouldUpdate: kotlin.Boolean,
    @Json(name = "language")
    val language: Language
) 



