/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import com.squareup.moshi.Json
/**
 * 
 * @param title 
 * @param email 
 * @param emailPlaceholder 
 * @param password 
 * @param passwordPlaceholder 
 * @param forgotButton 
 * @param authFailed 
 * @param loginButton 
 * @param yourEmail 
 * @param confirm 
 * @param forgot 
 * @param login 
 * @param invalidTitle 
 * @param invalidBody 
 * @param dontHaveAnAccount 
 */

data class Login (
    @Json(name = "title")
    val title: kotlin.String,
    @Json(name = "email")
    val email: kotlin.String,
    @Json(name = "emailPlaceholder")
    val emailPlaceholder: kotlin.String,
    @Json(name = "password")
    val password: kotlin.String,
    @Json(name = "passwordPlaceholder")
    val passwordPlaceholder: kotlin.String,
    @Json(name = "forgotButton")
    val forgotButton: kotlin.String,
    @Json(name = "authFailed")
    val authFailed: kotlin.String,
    @Json(name = "loginButton")
    val loginButton: kotlin.String,
    @Json(name = "yourEmail")
    val yourEmail: kotlin.String,
    @Json(name = "confirm")
    val confirm: kotlin.String,
    @Json(name = "forgot")
    val forgot: kotlin.String,
    @Json(name = "login")
    val login: kotlin.String,
    @Json(name = "invalidTitle")
    val invalidTitle: kotlin.String,
    @Json(name = "invalidBody")
    val invalidBody: kotlin.String,
    @Json(name = "dontHaveAnAccount")
    val dontHaveAnAccount: kotlin.String
) 



