/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import com.squareup.moshi.Json
/**
 * 
 * @param postSingular 
 * @param postPlural 
 * @param noPosts 
 * @param noUsers 
 * @param tags 
 * @param people 
 * @param categoryPopular 
 * @param categoryImages 
 * @param categoryArtists 
 * @param categoryShops 
 * @param categoryArticles 
 * @param categoryPeople 
 * @param topResult 
 * @param noResultsFor 
 * @param hereAreSomeSuggestions 
 * @param seeArticlesWithinTheseCategories 
 * @param seeTopArtistsWithTheseSkills 
 * @param weWereUnableToFindThisShopBut 
 * @param ourTeamWouldLoveToAddTheShopForYou 
 * @param yesPlease 
 * @param related 
 * @param filterByBodyPart 
 * @param letUsFindTheBestShops 
 * @param weNeedGPS 
 * @param giveAccess 
 * @param filterByStyle 
 * @param seeTopArtists 
 * @param noResults 
 * @param searchArticles 
 * @param sortBy 
 * @param filterByCategory 
 * @param recent 
 * @param popular 
 * @param searchArtists 
 * @param searchPeople 
 * @param searchImages 
 * @param searchTattoodo 
 * @param searchShops 
 * @param addShop 
 * @param shopName 
 * @param country 
 * @param city 
 * @param done 
 * @param youRock 
 * @param teamValidation 
 * @param backToDiscover 
 * @param kmAway 
 * @param doYouKnowThisShop 
 * @param letUsKnow 
 * @param book 
 * @param viewAll 
 * @param distanceKM 
 * @param distanceM 
 */

data class Search (
    @Json(name = "postSingular")
    val postSingular: kotlin.String,
    @Json(name = "postPlural")
    val postPlural: kotlin.String,
    @Json(name = "noPosts")
    val noPosts: kotlin.String,
    @Json(name = "noUsers")
    val noUsers: kotlin.String,
    @Json(name = "tags")
    val tags: kotlin.String,
    @Json(name = "people")
    val people: kotlin.String,
    @Json(name = "categoryPopular")
    val categoryPopular: kotlin.String,
    @Json(name = "categoryImages")
    val categoryImages: kotlin.String,
    @Json(name = "categoryArtists")
    val categoryArtists: kotlin.String,
    @Json(name = "categoryShops")
    val categoryShops: kotlin.String,
    @Json(name = "categoryArticles")
    val categoryArticles: kotlin.String,
    @Json(name = "categoryPeople")
    val categoryPeople: kotlin.String,
    @Json(name = "topResult")
    val topResult: kotlin.String,
    @Json(name = "noResultsFor")
    val noResultsFor: kotlin.String,
    @Json(name = "hereAreSomeSuggestions")
    val hereAreSomeSuggestions: kotlin.String,
    @Json(name = "seeArticlesWithinTheseCategories")
    val seeArticlesWithinTheseCategories: kotlin.String,
    @Json(name = "seeTopArtistsWithTheseSkills")
    val seeTopArtistsWithTheseSkills: kotlin.String,
    @Json(name = "weWereUnableToFindThisShopBut")
    val weWereUnableToFindThisShopBut: kotlin.String,
    @Json(name = "ourTeamWouldLoveToAddTheShopForYou")
    val ourTeamWouldLoveToAddTheShopForYou: kotlin.String,
    @Json(name = "yesPlease")
    val yesPlease: kotlin.String,
    @Json(name = "related")
    val related: kotlin.String,
    @Json(name = "filterByBodyPart")
    val filterByBodyPart: kotlin.String,
    @Json(name = "letUsFindTheBestShops")
    val letUsFindTheBestShops: kotlin.String,
    @Json(name = "weNeedGPS")
    val weNeedGPS: kotlin.String,
    @Json(name = "giveAccess")
    val giveAccess: kotlin.String,
    @Json(name = "filterByStyle")
    val filterByStyle: kotlin.String,
    @Json(name = "seeTopArtists")
    val seeTopArtists: kotlin.String,
    @Json(name = "noResults")
    val noResults: kotlin.String,
    @Json(name = "searchArticles")
    val searchArticles: kotlin.String,
    @Json(name = "sortBy")
    val sortBy: kotlin.String,
    @Json(name = "filterByCategory")
    val filterByCategory: kotlin.String,
    @Json(name = "recent")
    val recent: kotlin.String,
    @Json(name = "popular")
    val popular: kotlin.String,
    @Json(name = "searchArtists")
    val searchArtists: kotlin.String,
    @Json(name = "searchPeople")
    val searchPeople: kotlin.String,
    @Json(name = "searchImages")
    val searchImages: kotlin.String,
    @Json(name = "searchTattoodo")
    val searchTattoodo: kotlin.String,
    @Json(name = "searchShops")
    val searchShops: kotlin.String,
    @Json(name = "addShop")
    val addShop: kotlin.String,
    @Json(name = "shopName")
    val shopName: kotlin.String,
    @Json(name = "country")
    val country: kotlin.String,
    @Json(name = "city")
    val city: kotlin.String,
    @Json(name = "done")
    val done: kotlin.String,
    @Json(name = "youRock")
    val youRock: kotlin.String,
    @Json(name = "teamValidation")
    val teamValidation: kotlin.String,
    @Json(name = "backToDiscover")
    val backToDiscover: kotlin.String,
    @Json(name = "kmAway")
    val kmAway: kotlin.String,
    @Json(name = "doYouKnowThisShop")
    val doYouKnowThisShop: kotlin.String,
    @Json(name = "letUsKnow")
    val letUsKnow: kotlin.String,
    @Json(name = "book")
    val book: kotlin.String,
    @Json(name = "viewAll")
    val viewAll: kotlin.String,
    @Json(name = "distanceKM")
    val distanceKM: kotlin.String,
    @Json(name = "distanceM")
    val distanceM: kotlin.String
) 



