/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import com.squareup.moshi.Json
/**
 * 
 * @param search 
 * @param showActivity 
 * @param shareTattoo 
 * @param signIn 
 */

data class ShortcutMenu (
    @Json(name = "search")
    val search: kotlin.String,
    @Json(name = "showActivity")
    val showActivity: kotlin.String,
    @Json(name = "shareTattoo")
    val shareTattoo: kotlin.String,
    @Json(name = "signIn")
    val signIn: kotlin.String
) 



