/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import com.squareup.moshi.Json
/**
 * 
 * @param signUpWithEmail 
 * @param email 
 * @param password 
 * @param login 
 * @param signUp 
 * @param alreadyHaveAnAccount 
 * @param pleaseEnterValidEmail 
 * @param emailAlreadyTaken 
 * @param passwordTooShort 
 */

data class SignUp (
    @Json(name = "signUpWithEmail")
    val signUpWithEmail: kotlin.String,
    @Json(name = "email")
    val email: kotlin.String,
    @Json(name = "password")
    val password: kotlin.String,
    @Json(name = "login")
    val login: kotlin.String,
    @Json(name = "signUp")
    val signUp: kotlin.String,
    @Json(name = "alreadyHaveAnAccount")
    val alreadyHaveAnAccount: kotlin.String,
    @Json(name = "pleaseEnterValidEmail")
    val pleaseEnterValidEmail: kotlin.String,
    @Json(name = "emailAlreadyTaken")
    val emailAlreadyTaken: kotlin.String,
    @Json(name = "passwordTooShort")
    val passwordTooShort: kotlin.String
) 



