/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import com.squareup.moshi.Json
/**
 * 
 * @param addNewModalHeader 
 * @param deletePlatformModalText 
 * @param inProductionModalTextActivate 
 * @param inProductionModalTextDeactivate 
 * @param inProductionTooltipActivate 
 * @param inProductionTooltipDeactivate 
 * @param isInDevelopmentFlash 
 * @param isInProductionFlash 
 * @param keysTooltip 
 * @param platformLanguageTooltip 
 * @param title 
 */

data class TranslatePlatforms (
    @Json(name = "addNewModalHeader")
    val addNewModalHeader: kotlin.String,
    @Json(name = "deletePlatformModalText")
    val deletePlatformModalText: kotlin.String,
    @Json(name = "inProductionModalTextActivate")
    val inProductionModalTextActivate: kotlin.String,
    @Json(name = "inProductionModalTextDeactivate")
    val inProductionModalTextDeactivate: kotlin.String,
    @Json(name = "inProductionTooltipActivate")
    val inProductionTooltipActivate: kotlin.String,
    @Json(name = "inProductionTooltipDeactivate")
    val inProductionTooltipDeactivate: kotlin.String,
    @Json(name = "isInDevelopmentFlash")
    val isInDevelopmentFlash: kotlin.String,
    @Json(name = "isInProductionFlash")
    val isInProductionFlash: kotlin.String,
    @Json(name = "keysTooltip")
    val keysTooltip: kotlin.String,
    @Json(name = "platformLanguageTooltip")
    val platformLanguageTooltip: kotlin.String,
    @Json(name = "title")
    val title: kotlin.String
) 



