/**
* API
* This is the public API for nstack.io  Setup an application and use Application-Id and Rest-Api-Key
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dk.nodes.nstack.kotlin.codegen.model


import com.squareup.moshi.Json
/**
 * 
 * @param noLanguageConnection 
 * @param noLanguages 
 * @param noPlatforms 
 * @param platformIsInProduction 
 */

data class TranslateErrors (
    @Json(name = "noLanguageConnection")
    val noLanguageConnection: kotlin.String,
    @Json(name = "noLanguages")
    val noLanguages: kotlin.String,
    @Json(name = "noPlatforms")
    val noPlatforms: kotlin.String,
    @Json(name = "platformIsInProduction")
    val platformIsInProduction: kotlin.String
) 



